{
 "title": "Overview",
 "tags": [ "monitoring" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "Cluster", "query": "trilio_system_info" },
   {
    "name": "Scope",
    "query": "trilio_system_info{cluster=~\"$Cluster\"}"
   },
   {
    "name": "Install_Namespace",
    "label": "Install Namespace",
    "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Backup Summary",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(trilio_backup_info{ install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Restore Summary",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(trilio_restore_info{ install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (status) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Backup Plan Summary ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(trilio_backupplan_info{install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (applicationtype)",
     "legendFormat": "{{applicationtype}}"
    }
   ]
  },
  {
   "title": "TVK Health",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "trilio_component_status{install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Target Summary",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "count(trilio_target_info{install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (vendorType,status)"
    }
   ]
  },
  {
   "title": "TVK Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "trilio_system_info{ install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "TVK Scope",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "trilio_system_info{ install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  }
 ]
}