annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: DevGuard
  catalog.cattle.io/kube-version: '>=1.21-0'
  catalog.cattle.io/release-name: devguard
apiVersion: v2
appVersion: v1.9.0
description: A Helm chart for DevGuard — open-source software supply chain security,
  vulnerability management, and compliance.
home: https://devguard.org
icon: file://assets/icons/devguard.png
keywords:
- security
- developer-security-platform
- vulnerability-management
- devops
- supply-chain-security
- attestations
- in-toto
- csaf
- scanning
- compliance
kubeVersion: '>=1.21-0'
maintainers:
- email: info@l3montree.com
  name: L3montree GmbH
  url: https://l3montree.com
name: devguard
sources:
- https://github.com/l3montree-dev/devguard
- https://github.com/l3montree-dev/devguard-helm-chart
- https://docs.devguard.org
type: application
version: 1.9.0
