annotations:
  artifacthub.io/changes: "- \"chore(release): \U0001F680 publish traefik 39.0.2\"\n-
    \"docs: fix typo in examples\"\n- \"chore(deps): update helm/kind-action action
    to v1.14.0\"\n- \"feat: :package: allow IBM cloud values\"\n- \"chore(ci): lint
    on pr title\"\n"
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Traefik Proxy
  catalog.cattle.io/kube-version: '>=1.22.0-0'
  catalog.cattle.io/release-name: traefik
apiVersion: v2
appVersion: v3.6.8
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: file://assets/icons/traefik.png
keywords:
- traefik
- ingress
- networking
kubeVersion: '>=1.22.0-0'
maintainers:
- email: michel.loiseleur@traefik.io
  name: mloiseleur
- email: remi.buisson@traefik.io
  name: darkweaver87
- name: jnoordsij
name: traefik
sources:
- https://github.com/traefik/traefik-helm-chart
- https://github.com/traefik/traefik
type: application
version: 39.0.2
