annotations:
  artifacthub.io/changes: "- \"fix: remove Gateway API CRDs\"\n- \"feat(provider):
    :sparkles: support crossProviderNamespaces on kubernetes providers\"\n- \"feat(hub):
    :rocket: support traefik hub v3.20.2\"\n- \"chore(release): \U0001F680 publish
    40.2.0\"\n"
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Traefik Proxy
  catalog.cattle.io/kube-version: '>=1.25.0-0'
  catalog.cattle.io/release-name: traefik
  traefik.io/hub-max-version: v3.20.2
  traefik.io/hub-min-version: v3.19.3
  traefik.io/proxy-max-version: v3.7.1
  traefik.io/proxy-min-version: v3.6.0
apiVersion: v2
appVersion: v3.7.1
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: file://assets/icons/traefik.png
keywords:
- traefik
- ingress
- networking
kubeVersion: '>=1.25.0-0'
maintainers:
- email: michel.loiseleur@traefik.io
  name: mloiseleur
- email: remi.buisson@traefik.io
  name: darkweaver87
- name: jnoordsij
name: traefik
sources:
- https://github.com/traefik/traefik-helm-chart
- https://github.com/traefik/traefik
type: application
version: 40.2.0
