annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: DxOperator - SQL Server Availability Group
  catalog.cattle.io/kube-version: '>= 1.26.0-0'
  catalog.cattle.io/release-name: dxsqlag
  charts.openshift.io/name: DxOperator - SQL Server Availability Group
apiVersion: v2
appVersion: "26.0"
description: SQL Server Availability Groups using DH2i DxOperator
icon: file://assets/icons/dxsqlag.svg
kubeVersion: '>= 1.26.0-0'
maintainers:
- email: support@dh2i.com
  name: DH2i Company
  url: https://dh2i.com
name: dxsqlag
type: application
version: 1.0.0
