annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Nocoly HAP Single-Node
  catalog.cattle.io/kube-version: '>=1.23.0-0'
  catalog.cattle.io/namespace: nocoly
  catalog.cattle.io/release-name: hap-nocoly-single
apiVersion: v2
appVersion: 7.3.5
description: Nocoly HAP single-node deployment with app, sc, command, doc, and flink
  components
home: https://www.nocoly.com
icon: file://assets/icons/hap-nocoly-single.ico
kubeVersion: '>=1.23.0-0'
maintainers:
- email: ops@nocoly.com
  name: nocoly
name: hap-nocoly-single
sources:
- https://docs-pd.nocoly.com
version: 7.3.504
