annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: 'Update "engine" to 3.2.0.'
    - kind: changed
      description: 'Update engine to support a brand new API token authorization for Bitbucket Cloud'
    - kind: changed
      description: 'Update "pikolo" to 0.14.10.'
    - kind: changed
      description: 'Update "dind-volume-utils" to 1.30.5.'
    - kind: changed
      description: 'Update "compose" to 1.6.1.'
    - kind: changed
      description: 'Update "fs-ops" to 1.2.12.'
    - kind: changed
      description: 'Update "venona" to 2.0.8.'
    - kind: security
      description: 'Fix various security vulnerabilities in multiple runtime components.'
    - kind: security
      description: 'Fix various security vulnerabilities in venona.'
  artifacthub.io/containsSecurityUpdates: "true"
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Codefresh
  catalog.cattle.io/kube-version: '>=1.18-0'
  catalog.cattle.io/release-name: cf-runtime
apiVersion: v2
dependencies:
- name: cf-common
  repository: oci://quay.io/codefresh/charts
  version: 0.21.0
description: A Helm chart for Codefresh Runner
home: https://codefresh.io/
icon: file://assets/icons/cf-runtime.png
keywords:
- codefresh
- runner
kubeVersion: '>=1.18-0'
maintainers:
- name: codefresh
  url: https://codefresh-io.github.io/
name: cf-runtime
sources:
- https://github.com/codefresh-io/venona
version: 10.0.4
