{
 "title": "BackupPlan Detail",
 "tags": [ "logging" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "loki", "query": "loki" },
   { "name": "Cluster", "query": { "query": "trilio_system_info" } },
   {
    "name": "Scope",
    "query": {
     "query": "trilio_system_info{cluster=~\"$Cluster\"}"
    }
   },
   {
    "name": "Install_Namespace",
    "label": "Install Namespace",
    "query": {
     "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
    }
   },
   {
    "name": "BackupPlan",
    "label": "BackupPlan",
    "query": {
     "query": "trilio_backupplan_info{cluster=~\"$Cluster\"}"
    }
   },
   {
    "name": "Resource_Namespace",
    "label": "Resource Namespace",
    "query": {
     "query": "label_values({transaction_type=\"BackupPlan\", transaction_resource_name=~\"$BackupPlan\"},transaction_resource_namespace)"
    }
   },
   {
    "name": "transaction_id",
    "label": "Transaction ID",
    "query": "label_values({transaction_type=\"BackupPlan\", transaction_resource_name=~\"$BackupPlan\",transaction_resource_namespace=~\"$Resource_Namespace\"},transaction_id)"
   },
   {
    "name": "service_type",
    "label": "Service Type",
    "query": "label_values({transaction_type=\"BackupPlan\",transaction_resource_name=~\"$BackupPlan\",transaction_id=~\"$transaction_id\"}, service_type)"
   },
   {
    "name": "service_id",
    "label": "Service ID",
    "query": "label_values({transaction_type=\"BackupPlan\",transaction_resource_name=~\"$BackupPlan\",transaction_id=~\"$transaction_id\",service_type=~\"$service_type\"}, service_id)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1> Backup Plan Detail </h1></center>"
   }
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_backupplan_info{backupplan=~\"$BackupPlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Application Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_backupplan_info{ backupplan=~\"$BackupPlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Protected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_backupplan_info{ backupplan=~\"$BackupPlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Num of Backups",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_backupplan_info{ backupplan=~\"$BackupPlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_backupplan_info{ backupplan=~\"$BackupPlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Backups",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "trilio_backup_info{backupplan=~\"$BackupPlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "BackupPlan Logs",
   "type": "logs",
   "description": "BackupPlan Logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "{transaction_type=\"BackupPlan\",transaction_resource_name=~\"$BackupPlan\",transaction_id=~\"$transaction_id\",service_type=~\"$service_type\"}"
    }
   ]
  }
 ]
}