{
 "title": "Backup Detail",
 "tags": [ "logging" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "datasource", "query": "loki" },
   { "name": "Cluster", "query": { "query": "trilio_system_info" } },
   {
    "name": "Scope",
    "query": {
     "query": "trilio_system_info{cluster=~\"$Cluster\"}"
    }
   },
   {
    "name": "Install_Namespace",
    "label": "Install Namespace",
    "query": {
     "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
    }
   },
   {
    "name": "Backup",
    "label": "Backup",
    "query": {
     "query": "trilio_backup_info{cluster=~\"$Cluster\",install_namespace=~\"$Install_Namespace\"}"
    }
   },
   {
    "name": "Resource_Namespace",
    "label": "Resource Namespace",
    "query": "label_values({transaction_type=~\"Backup\",transaction_resource_name=~\"$Backup\"},transaction_resource_namespace)"
   },
   {
    "name": "transaction_id",
    "label": "Transaction ID",
    "query": "label_values({transaction_type=~\"Backup\",transaction_resource_name=~\"$Backup\",transaction_resource_namespace=~\"$Resource_Namespace\"},transaction_id)"
   },
   {
    "name": "service_type",
    "label": "Service Type",
    "query": "label_values({transaction_type=~\"Backup\",transaction_resource_name=~\"$Backup\",transaction_id=~\"$transaction_id\"}, service_type)"
   },
   {
    "name": "service_id",
    "label": "Service ID",
    "query": "label_values({transaction_type=~\"Backup\",transaction_resource_name=~\"$Backup\",transaction_id=~\"$transaction_id\",service_type=~\"$service_type\"}, service_id)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1> Backup Detail</h1></center>"
   }
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "trilio_backup_status_percentage{backup=~\"$Backup\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 8, "y": 2 },
   "targets": [
    {
     "expr": "trilio_backup_info{backup=~\"$Backup\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Metadata Info",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "avg(trilio_backup_metadata_info{backup=~\"$Backup\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (objecttype, applicationtype)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_backup_info{backup=~\"$Backup\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_backup_info{ backup=~\"$Backup\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Backup Plan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_backup_info{ backup=~\"$Backup\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "trilio_backup_info{ backup=~\"$Backup\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Backup Logs",
   "type": "logs",
   "description": "Backup Logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{transaction_type=\"Backup\",transaction_resource_name=~\"$Backup\",transaction_id=~\"$transaction_id\",service_type=~\"$service_type\",service_id=~\"$service_id\"}"
    }
   ]
  }
 ]
}