{
 "title": "Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "Cluster", "query": { "query": "trilio_system_info" } },
   {
    "name": "Scope",
    "query": {
     "query": "trilio_system_info{cluster=~\"$Cluster\"}"
    }
   },
   {
    "name": "Install_Namespace",
    "label": "Install Namespace",
    "query": {
     "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1><img src=\"https://connect.trilio.io/hs-fs/hubfs/Trilio%20Final%20Logo%20WHITE_Large.png\"></img>  </h1></center>"
   }
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "trilio_component_status", "legendFormat": "{{deployment}}-{{status}}" }
   ]
  },
  {
   "title": "TVK Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_system_info{ install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "TVK Scope",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_system_info{ install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Backup Summary",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(trilio_backup_info{ install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Restore Summary",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(trilio_restore_info{ install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (status) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Backup Plan Summary ",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(trilio_backupplan_info{install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (application)",
     "legendFormat": "{{applicationtype}}"
    }
   ]
  },
  {
   "title": "TVK Health",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "trilio_component_status{install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Target Summary",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "count(trilio_target_info{install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (vendorType,status)"
    }
   ]
  }
 ]
}