{{- if not .Values.apiserver.servingCerts.certManager.enabled }}
{{ template "operator-shard-manager.prepare-certs" $ }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operator-shard-manager.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator-shard-manager.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $._caCrt }}
  tls.crt: {{ $._serverCrt }}
  tls.key: {{ $._serverKey }}
{{- end }}
