{{- if .Values.license.create }}
{{- if not .Values.license.value }}
{{- fail "license.value is required when license.create is true" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kyverno-notation-aws.license.secretName" . }}
  namespace: {{ template "kyverno-notation-aws.namespace" . }}
  labels:
    {{- include "kyverno-notation-aws.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ default "license" .Values.license.key }}: {{ .Values.license.value | quote }}
{{- end }}
