annotations:
  charts.openshift.io/name: kubedb-migrator
apiVersion: v2
appVersion: v0.4.0
description: A Helm chart for Kubernetes
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
kubeVersion: '>=1.28.0-0'
maintainers:
- email: support@appscode.com
  name: appscode
name: kubedb-migrator
sources:
- https://github.com/kubedb/migrator-operator
type: application
version: v0.4.0
