annotations:
  artifacthub.io/changes: "- \"fix(providers.kubernetesIngressNGINX): :bug: clarify
    int defaults\"\n- \"feat: add service.nameOverride for adopting existing Services\"\n-
    \"feat(chart): \U0001F4DD version support with annotations\"\n- \"feat(deps):
    update traefik docker tag to v3.7.0-rc.1\"\n- \"feat(CRDs): add traefik hub ContentItem\"\n-
    \"feat(CRDs): update Traefik Hub to v1.29.0\"\n- \"feat(hub): ✨ expose multicluster
    serversTransport TLS and timeout options\"\n- \"feat(hub): ✨ support Nutanix Prism
    Central provider\"\n- \"feat(hub): \U0001F371 map Traefik Hub v3.20.0-ea.7+ to
    Traefik Proxy v3.7.0-rc.1\"\n- \"feat(nginx): ✨ support globalAuthUrl option\"\n-
    \"feat(nginx): ✨ support modsec option\"\n- \"feat(providers): ✨ support precedence
    option\"\n- \"feat(proxy): add support of kubernetesIngressNGINX.ipAllowListStrategy\"\n-
    \"feat(image): add image.digest for digest-based pinning\"\n- \"feat(deps): support
    traefik v3.7.0 & hub v3.20.0\"\n- \"chore(release): \U0001F680 publish traefik
    40.0.0 and crds 1.18.0\"\n"
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Traefik Proxy
  catalog.cattle.io/kube-version: '>=1.25.0-0'
  catalog.cattle.io/release-name: traefik
  traefik.io/hub-max-version: v3.20.0
  traefik.io/hub-min-version: v3.19.3
  traefik.io/proxy-max-version: v3.7.0
  traefik.io/proxy-min-version: v3.6.0
apiVersion: v2
appVersion: v3.7.0
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: file://assets/icons/traefik.png
keywords:
- traefik
- ingress
- networking
kubeVersion: '>=1.25.0-0'
maintainers:
- email: michel.loiseleur@traefik.io
  name: mloiseleur
- email: remi.buisson@traefik.io
  name: darkweaver87
- name: jnoordsij
name: traefik
sources:
- https://github.com/traefik/traefik-helm-chart
- https://github.com/traefik/traefik
type: application
version: 40.0.0
