{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alchemi-compute-api.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "alchemi-compute-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
