{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alchemi-worker.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "alchemi-worker.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
type: Opaque
stringData:
  {{- range $key, $val := .Values.secret.data }}
  {{- if $val }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
{{- end }}
