apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
  {{- if .Values.observability.serviceMonitor.enabled }}
  - name: metrics
    port: 9187
    targetPort: 9187
  {{- end }}
  selector:
    app: postgresql
