apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
data:
  postgresql.conf: |
    # -----------------------------
    # Connection Settings
    # -----------------------------
    listen_addresses = '*'
    max_connections = {{ .Values.postgresql.config.maxConnections }}

    # -----------------------------
    # Memory
    # -----------------------------
    shared_buffers = {{ .Values.postgresql.config.sharedBuffers }}
    huge_pages = try
    work_mem = {{ .Values.postgresql.config.workMem }}
    maintenance_work_mem = {{ .Values.postgresql.config.maintenanceWorkMem }}
    dynamic_shared_memory_type = posix

    # -----------------------------
    # Asynchronous Behavior
    # -----------------------------
    effective_io_concurrency = {{ .Values.postgresql.config.effectiveIoConcurrency }}
    max_worker_processes = {{ .Values.postgresql.config.maxWorkerProcesses }}
    max_parallel_workers_per_gather = 2
    max_parallel_workers = {{ .Values.postgresql.config.maxParallelWorkers }}
    max_parallel_maintenance_workers = 2

    # -----------------------------
    # Write-Ahead Log
    # -----------------------------
    wal_buffers = {{ .Values.postgresql.config.walBuffers }}
    checkpoint_completion_target = 0.9
    min_wal_size = {{ .Values.postgresql.config.minWalSize }}
    max_wal_size = {{ .Values.postgresql.config.maxWalSize }}

    # -----------------------------
    # Query Planner
    # -----------------------------
    random_page_cost = {{ .Values.postgresql.config.randomPageCost }}
    effective_cache_size = {{ .Values.postgresql.config.effectiveCacheSize }}
    default_statistics_target = 100

    # -----------------------------
    # Locale and Formatting
    # -----------------------------
    log_timezone = 'Etc/UTC'
    datestyle = 'iso, mdy'
    timezone = 'Etc/UTC'
    lc_messages = 'en_US.UTF-8'
    lc_monetary = 'en_US.UTF-8'
    lc_numeric = 'en_US.UTF-8'
    lc_time = 'en_US.UTF-8'
    default_text_search_config = 'pg_catalog.english'
