{{- if .Values.observability.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgresql
  labels:
    {{- include "devguard.labels" . | nindent 4 }}
    {{- with .Values.observability.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: postgresql
  endpoints:
  - port: metrics
    path: /metrics
    interval: {{ .Values.observability.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.observability.serviceMonitor.scrapeTimeout }}
{{- end }}
