annotations:
  charts.openshift.io/name: kubedb-autoscaler
apiVersion: v2
appVersion: v0.51.0
dependencies:
- condition: storage-metrics-server.enabled
  name: storage-metrics-server
  repository: oci://ghcr.io/appscode-charts
  version: v0.1.0
description: KubeDB Autoscaler by AppsCode - Autoscale KubeDB operated Databases
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
kubeVersion: '>=1.26.0-0'
maintainers:
- email: support@appscode.com
  name: appscode
name: kubedb-autoscaler
sources:
- https://github.com/kubedb
version: v0.51.0
