{{- if .Values.controllerManager.create -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-controller-manager-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.controllerManager.service.https.type }}
  ports:
  - port: {{ .Values.controllerManager.service.https.port }}
    targetPort: {{ .Values.controllerManager.service.https.port }}
    protocol: TCP
    name: https
  selector:
    {{- with .Values.controllerManager.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
