{{- if .Values.controllerManager.create -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-controller-manager-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-controller-manager-crt
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - localhost
  - harikube-controller-manager-svc
  - harikube-controller-manager-svc.{{ .Release.Namespace }}
  - harikube-controller-manager-svc.{{ .Release.Namespace }}.svc
  - harikube-controller-manager-svc.{{ .Release.Namespace }}.cluster.local
  - harikube-controller-manager-svc.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: harikube-controller-manager-issuer
  secretName: harikube-controller-manager-crt
{{- end }}
