{{- if .Values.middleware.create -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-middleware-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.middleware.service.apiPort.type }}
  ports:
  - port: {{ .Values.middleware.service.apiPort.port }}
    targetPort: {{ .Values.middleware.service.apiPort.port }}
    protocol: TCP
    name: api-port
  selector:
    {{- with .Values.middleware.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{ if .Values.middleware.monitoring.create }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  name: harikube-middleware-metrics-svc
spec:
  type: {{ .Values.middleware.service.metrics.type }}
  ports:
  - port: {{ .Values.middleware.service.metrics.port }}
    targetPort: {{ .Values.middleware.service.metrics.port }}
    protocol: TCP
    name: metrics
  selector:
    {{- with .Values.middleware.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{ end }}
{{- end }}
