{{- if .Values.operator.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-operator-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/finalizers
  verbs:
  - update
- apiGroups:
  - harikube.info
  resources:
  - topologyconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harikube.info
  resources:
  - topologyconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - harikube.info
  resources:
  - topologyconfigs/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-operator-metrics-auth-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-operator-topologyconfig-admin-role
rules:
- apiGroups:
  - harikube.info
  resources:
  - topologyconfigs
  verbs:
  - '*'
- apiGroups:
  - harikube.info
  resources:
  - topologyconfigs/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-operator-topologyconfig-editor-role
rules:
- apiGroups:
  - harikube.info
  resources:
  - topologyconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harikube.info
  resources:
  - topologyconfigs/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-operator-topologyconfig-viewer-role
rules:
- apiGroups:
  - harikube.info
  resources:
  - topologyconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - harikube.info
  resources:
  - topologyconfigs/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-operator-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: harikube-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: harikube-operator-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: harikube-operator-manager-role
subjects:
- kind: ServiceAccount
  name: harikube-operator-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: harikube-operator-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: harikube-operator-sa
  namespace: {{ .Release.Namespace }}
{{- end }}
