{{- if .Values.operator.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-operator-sa
  namespace: {{ .Release.Namespace }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
