apiVersion: v2
appVersion: 1.0.5
description: Alchemi Web frontend (Next.js)
home: https://alchemistudio.ai
keywords:
- alchemi
- web
- frontend
maintainers:
- name: Alchemi Platform Team
name: alchemi-web
type: application
version: 1.0.5
