apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubedb-gitops.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubedb-gitops.labels" . | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "kubedb-gitops.labels" . | nindent 4 }}
