{
 "title": "BackupPlan Detail",
 "tags": [ "monitoring" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "Cluster", "query": "trilio_system_info" },
   {
    "name": "Scope",
    "query": "trilio_system_info{cluster=~\"$Cluster\"}"
   },
   {
    "name": "Install_Namespace",
    "label": "Install Namespace",
    "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
   },
   {
    "name": "BackupPlan",
    "label": "BackupPlan",
    "query": "trilio_backupplan_info{cluster=~\"$Cluster\",install_namespace=~\"$Install_Namespace\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1> Backup Plan Detail </h1></center>"
   },
   "content": "<center><h1> Backup Plan Detail </h1></center>"
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_backupplan_info{backupplan=~\"$BackupPlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Application Type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "trilio_backupplan_info{ backupplan=~\"$BackupPlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Protected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "trilio_backupplan_info{ backupplan=~\"$BackupPlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Num of Backups",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "trilio_backupplan_info{ backupplan=~\"$BackupPlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Target",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "trilio_backupplan_info{ backupplan=~\"$BackupPlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Backups",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "trilio_backup_info{backupplan=~\"$BackupPlan\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  }
 ]
}