annotations:
  charts.openshift.io/name: petset
apiVersion: v1
appVersion: v0.0.16
description: Petset Operator by AppsCode
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/stash/petset-icon.png
kubeVersion: '>=1.28.0-0'
maintainers:
- email: support@appscode.com
  name: appscode
name: petset
sources:
- https://github.com/stashed
version: v2026.2.16
