{{- if .Values.license.create }}
{{- if not .Values.license.value }}
{{- fail "license.value is required when license.create is true" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kyverno.license.secretName" . }}
  namespace: {{ template "kyverno.namespace" . }}
  labels:
    {{- include "kyverno.config.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ default "license" .Values.license.key }}: |
{{ .Values.license.value | indent 4 }}
{{- end }}
