apiVersion: apps/v1
kind: Deployment
metadata: { name: command, labels: { app: command } }
spec:
  replicas: 1
  selector: { matchLabels: { app: command } }
  template:
    metadata: { labels: { app: command } }
    spec:
      containers:
        - name: command
          image: "{{ .Values.images.registry }}/{{ .Values.images.command }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.resources.command.cpu | quote }}
              memory: {{ .Values.resources.command.memory | quote }}
---
apiVersion: v1
kind: Service
metadata: { name: command }
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector: { app: command }
