apiVersion: apps/v1
kind: Deployment
metadata: { name: doc, labels: { app: doc } }
spec:
  replicas: 1
  selector: { matchLabels: { app: doc } }
  template:
    metadata: { labels: { app: doc } }
    spec:
      containers:
        - name: doc
          image: "{{ .Values.images.registry }}/{{ .Values.images.doc }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.resources.doc.cpu | quote }}
              memory: {{ .Values.resources.doc.memory | quote }}
---
apiVersion: v1
kind: Service
metadata: { name: doc }
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector: { app: doc }
