apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hap-shared-data
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.sharedDataSize | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hap-data
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.hapDataSize | quote }}
