{{- if .Values.features.csiDriverIntegration }}
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: kopia-snapshot-class
  annotations:
    k10.kasten.io/is-snapshot-class: "true"
  labels:
    {{- include "backup-csi-driver.labels" . | nindent 4 }}
driver: {{ include "backup-csi-driver.driverName" . }}
deletionPolicy: Retain
{{- end }}
