annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: Ensure spec.template.metadata isn't null
    - kind: removed
      description: Remove the `delete` permission for policyexceptions in the admission controller
    - kind: changed
      description: Enable the flag `--generateValidatingAdmissionPolicy` by default in the admission controller.
    - kind: changed
      description: Enable the flag `--validatingAdmissionPolicyReports` by default in the reports controller.
  artifacthub.io/links: |
    - name: Documentation
      url: https://kyverno.io/docs
    - name: Nirmata Enterprise Software License Agreement (EULA)
      url: https://nirmata.com/eula/
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Nirmata Kyverno
  catalog.cattle.io/kube-version: '>=1.25.0-0'
  catalog.cattle.io/release-name: kyverno
  nirmata.com/eula: https://nirmata.com/eula/
apiVersion: v2
appVersion: v1.17.0-n4k.nirmata.3
dependencies:
- condition: grafana.enabled
  name: grafana
  repository: ""
  version: 3.7.0
- condition: crds.install
  name: crds
  repository: ""
  version: 3.7.0
- condition: crds.install
  name: kyverno-api
  repository: https://kyverno.github.io/api
  version: 0.0.1-alpha.1
- condition: reports-server.install
  name: reports-server
  repository: https://nirmata.github.io/kyverno-charts
  version: 0.2.28
- condition: openreports.installCrds
  name: openreports
  repository: https://openreports.github.io/reports-api
  version: 0.1.0
description: Kubernetes Native Policy Management
home: https://nirmata.com/
icon: file://assets/icons/kyverno.png
keywords:
- kubernetes
- nirmata
- policy agent
- policy
- validating webhook
- admission controller
- mutation
- mutate
- validate
- generate
- supply chain
- security
kubeVersion: '>=1.25.0-0'
maintainers:
- name: Nirmata
  url: https://nirmata.com/
name: kyverno
sources:
- https://github.com/nirmata/enterprise-kyverno
type: application
version: 3.7.3
