{{- if and .Values.gatewayClass .Values.gatewayClass.create }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayClass.name }}
  labels:
    {{- include "airlock-microgateway.labels" $ | nindent 4 }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  controllerName: {{ .Values.controllerName }}
  description: GatewayClass for Airlock Microgateway.
{{- end }}