{{- if .Values.api.intoto.generate }}
{{- $secretName := .Values.api.intoto.existingPrivateKeySecretName -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "devguard.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and $existing (index $existing.data "privateKey") }}
  privateKey: {{ index $existing.data "privateKey" | b64dec | quote }}
  {{- else }}
  privateKey: {{ genPrivateKey "ecdsa" | quote }}
  {{- end }}
{{- end }}
