# NOTE:  If cert-manager is enabled, ingress annotations create our Dex certificate by specifying an issuer
{{- if not .Values.certManager.enabled }}
{{- if .Values.global.dex.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  annotations:
  name: dex-tls
  namespace: {{ .Release.Namespace }}
stringData:
  ca.crt:  {{ .Values.certManager.dex.ca   | default .Values.certManager.epinio.ca   | quote }}
  tls.key: {{ .Values.certManager.dex.key  | default .Values.certManager.epinio.key  | quote }}
  tls.crt: {{ .Values.certManager.dex.cert | default .Values.certManager.epinio.cert | quote }}
{{- end }}
{{- end }}