# TODO: Add cert-manager option of handling for s3gw certificate
{{- if not .Values.certManager.enabled }}
{{- if and .Values.seaweedfs.enabled .Values.seaweedfs.tls.enabled .Values.seaweedfs.global.enableSecurity }}
{{- else if  .Values.s3gw.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  annotations:
  name: s3gw-cluster-ip-tls
  namespace: {{ .Release.Namespace }}
stringData:
  ca.crt: {{ .Values.certManager.s3.ca | quote }}
  tls.key: {{ .Values.certManager.s3.key | quote }}
  tls.crt: {{ .Values.certManager.s3.cert | quote }}
{{- end }}
{{- end }}