apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  {{- with .Values.postgresql.pvc.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.pvc.size | quote }}
