{{- if .Values.apiServer.create -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-api-server-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.apiServer.service.apiServer.type }}
  ports:
  - port: {{ .Values.apiServer.service.apiServer.port }}
    targetPort: {{ .Values.apiServer.service.apiServer.port }}
    protocol: TCP
    name: api-server
  selector:
    {{- with .Values.apiServer.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
