{{- if .Values.apiServer.create -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-api-server-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-api-server-crt
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - kubernetes.default.svc.cluster.local, kubernetes.default.svc
  - kubernetes.default
  - kubernetes
  - localhost
  - "*.harikube.{{ .Release.Namespace }}.nodes.vcluster.com"
  - "*.nodes.vcluster.com"
  - harikube
  - harikube.{{ .Release.Namespace }}
  - harikube-api-server-svc.{{ .Release.Namespace }}
  - harikube-api-server-svc.{{ .Release.Namespace }}.svc
  - harikube-api-server-svc.{{ .Release.Namespace }}.cluster.local
  - harikube-api-server-svc.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: harikube-api-server-issuer
  secretName: harikube-api-server-crt
{{- end }}
