{{- if .Values.enterprise.key -}}
apiVersion: v1
kind: Secret
metadata:
  name: harikube-license
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  license: {{ .Values.enterprise.key | b64enc | quote }}
{{- end }}
---
{{- if .Values.enterprise.user -}}
apiVersion: v1
kind: Secret
metadata:
  name: harikube-registry-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"registry.harikube.info\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.enterprise.user .Values.enterprise.password (printf "%s:%s" .Values.enterprise.user .Values.enterprise.password | b64enc) | b64enc | quote }}
{{- end }}