{{- if .Values.middleware.endPoint.caPEM }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "harikube.labels" . | nindent 4 }}
  name: harikube-middleware-endpoint-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.middleware.endPoint.caPEM | b64enc }}
  tls.crt: {{ .Values.middleware.endPoint.certPEM | b64enc }}
  tls.key: {{ .Values.middleware.endPoint.keyPEM | b64enc }}
{{- end }}