annotations:
  charts.openshift.io/name: supervisor
apiVersion: v2
appVersion: v0.0.12
description: A Helm chart for Supervisor by AppsCode
home: https://github.com/kubeops/supervisor
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
kubeVersion: '>=1.28.0-0'
maintainers:
- email: support@appscode.com
  name: appscode
name: supervisor
sources:
- https://github.com/kubeops/supervisor
type: application
version: v2026.2.16
