{
 "title": "Airlock Microgateway License",
 "tags": [ "airlock-microgateway" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "operator_namespace",
    "label": "Operator Namespace",
    "query": {
     "query": "label_values(microgateway_license_valid,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "License Status",
   "type": "stat",
   "description": "License status of Airlock Microgateway.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(microgateway_license_valid{namespace=~\"${operator_namespace.regex}\"})",
     "legendFormat": "License Status"
    }
   ]
  },
  {
   "title": "License Expiry Date",
   "type": "stat",
   "description": "Expiry date of the Airlock Microgateway license associated with the selected operator.",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "time: L" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(microgateway_license_expiry_timestamp_seconds{namespace=~\"${operator_namespace.regex}\"})*1000",
     "legendFormat": "Expiry Date (MM/DD/YYYY)"
    }
   ]
  },
  {
   "title": "Licensed Requests",
   "type": "stat",
   "description": "Number of licensed requests for applications protected by Airlock Microgateway.",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(microgateway_license_max_rq_count_per_month{namespace=~\"${operator_namespace.regex}\"})",
     "legendFormat": "Licensed Requests"
    }
   ]
  },
  {
   "title": "Requests over 30 days (estimated)",
   "type": "stat",
   "description": "Estimated number of requests protected by Airlock Microgateway over 30 days based on the last 7 days.",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(microgateway_license_http_rq_total{job=~\"${operator_namespace.regex}/.*-engine\"}[7d]))/7*30",
     "legendFormat": "Estimated Requests"
    }
   ]
  },
  {
   "title": "Processed Requests per week",
   "type": "timeseries",
   "description": "Number of requests per week processed by Airlock Microgateway.",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(increase(microgateway_license_http_rq_total{job=~\"${operator_namespace.regex}/.*-engine\"}[7d])[2m:30s]))",
     "legendFormat": "# Requests per week"
    }
   ]
  }
 ]
}