{{- if .Values.features.csiDriverIntegration }}
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ include "backup-csi-driver.driverName" . }}
  labels:
    {{- include "backup-csi-driver.labels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Ephemeral
    - Persistent
  fsGroupPolicy: None
{{- end }}
