{{- if .Values.features.csiDriverIntegration }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backup-csi-driver.fullname" . }}-snapshot
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backup-csi-driver.labels" . | nindent 4 }}
    app.kubernetes.io/component: node
spec:
  clusterIP: None
  selector:
    {{- include "backup-csi-driver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: node
  ports:
    - name: snapshot-grpc
      port: {{ include "backup-csi-driver.snapshotPort" . }}
      targetPort: snapshot-grpc
      protocol: TCP
{{- end }}
