apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-with-vac
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: powerflex-sc
  resources:
    requests:
      storage: 10Gi
  volumeAttributesClassName: vac-qos
