apiVersion: storage.k8s.io/v1
kind: VolumeAttributesClass
metadata:
  name: vac-qos
driverName: csi-vxflexos.dellemc.com
parameters:
  # QoS limits for PowerFlex volumes
  iopsLimit: "500"
  bandwidthLimitInKbps: "1024"
