apiVersion: storage.k8s.io/v1
kind: VolumeAttributesClass
metadata:
  name: vac-qos-unlimited
driverName: csi-vxflexos.dellemc.com
parameters:
  # Unlimited QoS settings for PowerFlex volumes
  iopsLimit: "0"
  bandwidthLimitInKbps: "0"
