{
 "title": "ConsistentSet Detail",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "datasource", "query": "loki" },
   { "name": "Cluster", "query": { "query": "trilio_system_info" } },
   {
    "name": "Scope",
    "query": {
     "query": "trilio_system_info{cluster=~\"$Cluster\"}"
    }
   },
   {
    "name": "Install_Namespace",
    "label": "Install Namespace",
    "query": {
     "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
    }
   },
   {
    "name": "service_type",
    "label": "Service Type",
    "query": "label_values({child_transaction_resource_name=\"$ConsistentSet\",child_transaction_type=\"ConsistentSet\",transaction_resource_name=\"$ContinuousRestorePlan\",transaction_type=\"ContinuousRestorePlan\"}, service_type)"
   },
   {
    "name": "ConsistentSet",
    "label": "ConsistentSet",
    "query": {
     "query": "trilio_consistentset_info{cluster=~\"$Cluster\",install_namespace=~\"$Install_Namespace\",kind=\"ConsistentSet\"}"
    }
   },
   {
    "name": "ContinuousRestorePlan",
    "label": "ContinuousRestorePlan",
    "query": {
     "query": "trilio_continuousrestoreplan_info{cluster=~\"$Cluster\",kind=\"ContinuousRestorePlan\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>ConsistentSet Detail</h1></center>"
   }
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "trilio_consistentset_status_percentage{consistentset=~\"$ConsistentSet\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"ConsistentSet\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 8, "y": 2 },
   "targets": [
    {
     "expr": "trilio_consistentset_info{consistentset=~\"$ConsistentSet\",cluster=~\"$Cluster\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "ConsistentSet Logs",
   "type": "logs",
   "description": "ConsistentSet Logs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "{child_transaction_resource_name=\"$ConsistentSet\",child_transaction_type=\"ConsistentSet\",transaction_resource_name=\"$ContinuousRestorePlan\",transaction_type=\"ContinuousRestorePlan\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_consistentset_info{consistentset=~\"$ConsistentSet\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"ConsistentSet\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_consistentset_info{ consistentset=~\"$ConsistentSet\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"ConsistentSet\"}"
    }
   ]
  },
  {
   "title": "ContinuousRestorePlan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_consistentset_info{consistentset=~\"$ConsistentSet\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"ConsistentSet\"}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "trilio_consistentset_info{ consistentset=~\"$ConsistentSet\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\",kind=\"ConsistentSet\"}"
    }
   ]
  }
 ]
}