apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alchemi-compute-api.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "alchemi-compute-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  {{- toYaml .Values.config | nindent 2 }}
