{{/* AUTOGENERATED FILE DO NOT EDIT */}}

{{/*
Operator rbac permission rules
*/}}
{{- define "airlock-microgateway-operator.rbacRules" -}}
- apiGroups:
    - ""
  resources:
    - configmaps
    - namespaces
    - nodes
    - replicasets
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - pods/finalizers
  verbs:
    - update
- apiGroups:
    - ""
  resources:
    - pods/status
  verbs:
    - patch
    - update
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - replicasets
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - replicasets/finalizers
  verbs:
    - patch
    - update
- apiGroups:
    - gateway.networking.k8s.io
  resources:
    - gatewayclasses
  verbs:
    - get
    - list
    - patch
    - watch
- apiGroups:
    - gateway.networking.k8s.io
  resources:
    - gatewayclasses/finalizers
    - gatewayclasses/status
    - gateways/finalizers
    - gateways/status
    - httproutes/status
  verbs:
    - patch
    - update
- apiGroups:
    - gateway.networking.k8s.io
  resources:
    - gateways
    - httproutes
    - referencegrants
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - gateway.networking.k8s.io
    - x-openshift.microgateway.airlock.com
  resources:
    - backendtlspolicies
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - gateway.networking.k8s.io
    - x-openshift.microgateway.airlock.com
  resources:
    - backendtlspolicies/status
  verbs:
    - patch
    - update
- apiGroups:
    - microgateway.airlock.com
  resources:
    - accesscontrolpolicies
    - accesscontrols
    - apiprotections
    - contentsecurities
    - contentsecuritypolicies
    - csrfprotections
    - denyrules
    - envoyclusters
    - envoyextensionpolicies
    - envoyhttpfilters
    - gatewayparameters
    - graphqls
    - headerrewrites
    - identitypropagations
    - jwks
    - jwts
    - limits
    - oidcproviders
    - oidcrelyingparties
    - openapis
    - parsers
    - redisproviders
    - sessionhandlings
    - telemetries
    - tokenexchanges
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - accesscontrolpolicies/status
    - contentsecuritypolicies/status
    - envoyextensionpolicies/status
  verbs:
    - patch
    - update
- apiGroups:
    - microgateway.airlock.com
  resources:
    - envoyconfigurations
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - envoyconfigurations/status
    - sidecargateways/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - microgateway.airlock.com
  resources:
    - sidecargateways
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - sidecargateways/finalizers
  verbs:
    - update
- apiGroups:
    - monitoring.coreos.com
  resources:
    - podmonitors
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
{{- end }}
