annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: |
       fix(openshift): update readinessProbe to support horizontal scalability
    - kind: fixed
      description: |
        fix: Add global imagePullSecrets to Snapshot CronJob
    - kind: fixed
      description: |
        fix(openshift): use non certified quay.io ubi container image
    - kind: fixed
      description: |
        fix(chart): preserve custom BackendTLSPolicy validation hostname
    - kind: fixed
      description: |
        fix(httpRoute): template timeouts in rule
    - kind: fixed
      description: |
        fix: allow using custom Secret keys for Snapshot Agent S3 credentials.
    - kind: changed
      description: |
        feat: apply server.statefulset.securityContext on helm test pod
    - kind: changed
      description: |
        feat: Support bearerTokenFile for ServiceMonitor
    - kind: changed
      description: |
        chore: update openbao-snapshot-agent to version 0.4.0 and add additional configuration
    - kind: changed
      description: |
        chore: update to openbao-csi-provider 2.0.3
    - kind: changed
      description: |
        chore(chart): remove obsolete Kubernetes API and version compatibility checks
  artifacthub.io/containsSecurityUpdates: "true"
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: OpenBao
  catalog.cattle.io/kube-version: '>= 1.30.0-0'
  catalog.cattle.io/release-name: openbao
  charts.openshift.io/name: OpenBao
  charts.openshift.io/provider: OpenBao
apiVersion: v2
appVersion: v2.6.1
description: Official OpenBao Chart
home: https://github.com/openbao/openbao-helm
icon: file://assets/icons/openbao.svg
keywords:
- vault
- openbao
- security
- encryption
- secrets
- management
- automation
- infrastructure
kubeVersion: '>= 1.30.0-0'
maintainers:
- email: openbao-security@lists.openssf.org
  name: OpenBao
  url: https://openbao.org
name: openbao
sources:
- https://github.com/openbao/openbao-helm
version: 0.29.0
