{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alchemi-ai.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "alchemi-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
