annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Dynatrace Operator
  catalog.cattle.io/kube-version: '>=1.25.0-0'
  catalog.cattle.io/release-name: dynatrace-operator
apiVersion: v2
appVersion: 1.9.0
description: The Dynatrace Operator Helm chart for Kubernetes and OpenShift
home: https://www.dynatrace.com/
icon: file://assets/icons/dynatrace-operator.png
kubeVersion: '>=1.25.0-0'
maintainers:
- email: marcell.sevcsik@dynatrace.com
  name: 0sewa0
- email: andrii.soldatenko@dynatrace.com
  name: andriisoldatenko
- email: christoph.muellner@dynatrace.com
  name: chrismuellner
- email: george.balea@dynatrace.com
  name: geba-dyna
name: dynatrace-operator
sources:
- https://github.com/Dynatrace/dynatrace-operator
type: application
version: 1.9.0
