{
 "title": "Airlock Microgateway Threats LogOnly - Metrics",
 "description": "Metrics on threats logged by Airlock Microgateway in threat handling mode LogOnly.\n\nDashboard can be filtered by namespaces as well as block types.",
 "tags": [ "airlock-microgateway" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource Prometheus", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "DS_LOKI", "query": "loki" },
   {
    "name": "operator_namespace",
    "label": "Operator Namespace",
    "query": {
     "query": "label_values(microgateway_license_valid,namespace)"
    }
   },
   {
    "name": "namespace",
    "label": "Application Namespace",
    "query": {
     "query": "label_values(microgateway_license_http_rq_total,namespace)"
    }
   },
   {
    "name": "blockType",
    "label": "Block Type",
    "query": {
     "query": "label_values(microgateway_http_downstream_rq_threats_logged_total,block_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Airlock Microgateway Threats LogOnly - Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Threats - LogOnly",
   "type": "stat",
   "description": "Number of threats logged by Airlock Microgateway in threat handling mode LogOnly.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(microgateway_http_downstream_rq_threats_logged_total{block_type=~\"${blockType:regex}\", namespace=~\"${namespace:regex}\", job=~\"${operator_namespace.regex}/.*-engine\"}[$__range])))",
     "legendFormat": "Logged threats in LogOnly mode"
    }
   ]
  },
  {
   "title": "Threats - LogOnly",
   "type": "timeseries",
   "description": "Number of threats per second handled in LogOnly mode.",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(microgateway_http_downstream_rq_threats_logged_total{block_type=~\"${blockType:regex}\", namespace=~\"${namespace:regex}\", job=~\"${operator_namespace.regex}/.*-engine\"}[1m]))",
     "legendFormat": "Number of threats per second"
    }
   ]
  },
  {
   "title": "Block Type",
   "type": "barchart",
   "description": "Number of threats in LogOnly mode by block type.",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (block_type) (increase(microgateway_http_downstream_rq_threats_logged_total{block_type=~\"${blockType:regex}\", namespace=~\"${namespace:regex}\", job=~\"${operator_namespace.regex}/.*-engine\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Subtype",
   "type": "barchart",
   "description": "Number of threats in LogOnly mode by block subtype, which are subsets of the various block types.",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (block_subtype) (increase(microgateway_http_downstream_rq_threats_logged_total{block_type=~\"${blockType:regex}\", namespace=~\"${namespace:regex}\", job=~\"${operator_namespace.regex}/.*-engine\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}