{{/* AUTOGENERATED FILE DO NOT EDIT */}}

{{/*
Operator rbac permission rules
*/}}
{{- define "airlock-microgateway-operator.rbacRules" -}}
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - pods/finalizers
  verbs:
    - update
- apiGroups:
    - ""
  resources:
    - pods/status
  verbs:
    - patch
    - update
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - delete
    - get
    - list
    - update
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - accesscontrols
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - contentsecurities
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - denyrules
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - envoyclusters
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - envoyconfigurations
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - envoyconfigurations/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - microgateway.airlock.com
  resources:
    - envoyhttpfilters
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - graphqls
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - headerrewrites
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - identitypropagations
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - limits
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - oidcproviders
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - oidcrelyingparties
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - openapis
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - parsers
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - redisproviders
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - sessionhandlings
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - sidecargateways
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - microgateway.airlock.com
  resources:
    - sidecargateways/finalizers
  verbs:
    - update
- apiGroups:
    - microgateway.airlock.com
  resources:
    - sidecargateways/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - microgateway.airlock.com
  resources:
    - telemetries
  verbs:
    - get
    - list
    - watch
{{- end }}
