{
 "title": "K10 Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster" },
   { "name": "operation", "label": "operation", "query": { "query": "limiter_pending_count" } }
  ]
 },
 "panels": [
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backups Completed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_ended_overall{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Backups Failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_ended_overall{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Backups Skipped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_skipped_overall{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Restores Completed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_ended_overall{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Restores Failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_ended_overall{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Restores Skipped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_skipped_overall{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Cluster Backups Completed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_cluster_ended_overall{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster Backups Failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_cluster_ended_overall{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster Backups Skipped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_cluster_skipped_overall{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster Restores Completed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_cluster_ended_overall{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster Restores Failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_cluster_ended_overall{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster Restores Skipped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_cluster_skipped_overall{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  { "title": "Backup Exports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Exports Completed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_export_ended_overall{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Exports Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_export_ended_overall{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Exports Skipped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_export_skipped_overall{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Imports Completed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_import_ended_overall{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Imports Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_import_ended_overall{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Imports Skipped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_import_skipped_overall{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Policy Runs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "runs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_run_ended_overall{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Policy Runs Skipped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "runs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_run_skipped_overall{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Catalog Volume Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "catalog_persistent_volume_disk_space_used_bytes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Catalog Volume Used Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-catalog_persistent_volume_free_space_percent{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Jobs Volume Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_persistent_volume_disk_space_used_bytes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Jobs Volume Used Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-jobs_persistent_volume_free_space_percent{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Logging Volume Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logging_persistent_volume_disk_space_used_bytes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Logging Volume Used Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-logging_persistent_volume_free_space_percent{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Compliant Applications",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "compliance_count{state=\"Compliant\"}"
    }
   ]
  },
  {
   "title": "Non-Compliant Applications",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "compliance_count{state=\"NotCompliant\"}"
    }
   ]
  },
  {
   "title": "Unmanaged Applications",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "compliance_count{state=\"Unmanaged\"}"
    }
   ]
  },
  {
   "title": "Snapshot Size (Physical)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snapshot_storage_size_bytes{cluster=\"$cluster\", type=\"physical\"}"
    }
   ]
  },
  {
   "title": "Snapshot Size (Logical)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snapshot_storage_size_bytes{cluster=\"$cluster\", type=\"logical\"}"
    }
   ]
  },
  {
   "title": "Export Size (Physical)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "export_storage_size_bytes{cluster=\"$cluster\", type=\"physical\"}"
    }
   ]
  },
  {
   "title": "Export Size (Logical)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "export_storage_size_bytes{cluster=\"$cluster\", type=\"logical\"}"
    }
   ]
  },
  {
   "title": "Execution Control",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active Job Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum(exec_executor_worker_count)",
       "legendFormat": "Worker Count"
      },
      {
       "expr": "sum(exec_active_job_count) OR on() vector(0)",
       "legendFormat": "Active Job Count"
      }
     ]
    },
    {
     "title": "Rate Limiter - avg operation duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(limiter_request_seconds_sum{stage=\"hold\"}[5m])) by (operation) / sum(rate(limiter_request_seconds_count{stage=\"hold\"}[5m])) by (operation) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate Limiter - $operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4.8, "x": 0, "y": 45 },
     "repeat": "operation",
     "targets": [
      {
       "expr": "limiter_inflight_count{operation=\"$operation\"}",
       "legendFormat": "Inflight"
      },
      {
       "expr": "limiter_pending_count{operation=\"$operation\"}",
       "legendFormat": "Pending"
      },
      {
       "expr": "limiter_inflight_limit_value{operation=\"$operation\"}",
       "legendFormat": "Limit"
      }
     ]
    }
   ]
  }
 ]
}