apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alchemi-zenith.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "alchemi-zenith.labels" . | nindent 4 }}
    app: {{ include "alchemi-zenith.fullname" . }}
    alchemi.io/license-managed: "true"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "alchemi-zenith.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "alchemi-zenith.selectorLabels" . | nindent 8 }}
        app: {{ include "alchemi-zenith.fullname" . }}
        alchemi.io/license-managed: "true"
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.service.enabled }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.config.create .Values.secret.create .Values.envFrom }}
          envFrom:
            {{- if .Values.config.create }}
            - configMapRef:
                name: {{ include "alchemi-zenith.fullname" . }}-config
            {{- end }}
            {{- if .Values.secret.create }}
            - secretRef:
                name: {{ include "alchemi-zenith.fullname" . }}-secrets
            {{- end }}
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          {{- if .Values.probes.readiness }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      restartPolicy: Always
