apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "alchemi-keycloak.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "alchemi-keycloak.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        {{- include "alchemi-keycloak.selectorLabels" . | nindent 8 }}
      annotations:
        {{- if .Values.configChecksum }}
        checksum/config: {{ .Values.configChecksum | quote }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: keycloak
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - start
          ports:
            - name: http
              containerPort: {{ .Values.service.http.port }}
              protocol: TCP
            - name: https
              containerPort: {{ .Values.service.https.port }}
              protocol: TCP
            - name: management
              containerPort: {{ .Values.service.management.port }}
              protocol: TCP
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          env:
            {{- if .Values.dbUrlEnabled }}
            - name: KC_DB_URL
              value: "jdbc:postgresql://$(KC_DB_URL_HOST):$(KC_DB_URL_PORT)/$(KC_DB_URL_DATABASE)?sslmode=require"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          startupProbe:
            httpGet:
              path: /health/started
              port: {{ .Values.service.management.port }}
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: {{ .Values.service.management.port }}
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: {{ .Values.service.management.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
