{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "alchemi-keycloak.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "alchemi-keycloak.selectorLabels" . | nindent 6 }}
{{- end }}
