apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "alchemi-keycloak.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "alchemi-keycloak.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.service.https.port }}
      targetPort: https
      protocol: TCP
    - name: management
      port: {{ .Values.service.management.port }}
      targetPort: management
      protocol: TCP
