{
 "title": "Kasten / RED Metrics",
 "description": "HTTP RED metrics visualization for Kasten",
 "tags": [ "kasten" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "Service",
    "label": "Service",
    "query": {
     "query": "label_values({application=\"k10\"}, service_name)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values({application=\"k10\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({application=\"k10\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Slowest HTTP routes (P95)",
   "type": "table",
   "description": "the slowest HTTP routes sorted by response time percentile",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(topk by(http_route, service_name) (5,  max by (http_route, service_name) (histogram_quantile(0.95,  (sum by(http_route, service_name, le) (rate({__name__=~\"http_server_request_duration_seconds_bucket|http_server_request_duration_bucket\",application=\"k10\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])))))))",
     "legendFormat": "{{service_name}} - {{http_route}}"
    }
   ]
  },
  { "title": "Inbound: $Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "Service" },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "average and top percentiles for HTTP traffic",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(service_name, le) (rate({__name__=~\"http_server_request_duration_seconds_bucket|http_server_request_duration_bucket\",application=\"k10\",service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "HTTP p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate({__name__=~\"http_server_request_duration_seconds_bucket|http_server_request_duration_bucket\",application=\"k10\",service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) by (service_name, le))",
     "legendFormat": "HTTP p95"
    },
    {
     "expr": "sum(rate({__name__=~\"http_server_request_duration_seconds_sum|http_server_request_duration_sum\",application=\"k10\",service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) / sum(rate({__name__=~\"http_server_request_duration_seconds_count|http_server_request_duration_count\",application=\"k10\",service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval]))",
     "legendFormat": "HTTP Avg"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "number of requests per second, faceted by its HTTP return code",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"http_server_request_duration_seconds_count|http_server_request_duration_count\",application=\"k10\",service_name=\"$Service\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) by (http_response_status_code)",
     "legendFormat": "HTTP server - {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "description": "percentage of 4xx|5xx HTTP responses responses over the total of the requests",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (rate({__name__=~\"http_server_request_duration_seconds_count|http_server_request_duration_count\",application=\"k10\",service_name=\"${Service}\",http_response_status_code=~\"(4|5).*\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) / ignoring(http_response_status_code) group_left sum(rate({__name__=~\"http_server_request_duration_seconds_count|http_server_request_duration_count\",application=\"k10\",service_name=\"${Service}\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "HTTP server - {{http_response_status_code}}"
    }
   ]
  }
 ]
}