{
 "title": "BackupPlan Overview",
 "tags": [ "logging" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "Cluster", "query": "trilio_system_info" },
   {
    "name": "Scope",
    "query": "trilio_system_info{cluster=~\"$Cluster\"}"
   },
   {
    "name": "Install_Namespace",
    "label": "Install Namespace",
    "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
   },
   { "name": "ApplicationType", "label": "Application Type", "query": "trilio_backupplan_info" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1> Backup Plan Overview </h1></center>"
   },
   "content": "<center><h1> Backup Plan Overview </h1></center>"
  },
  {
   "title": "All",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(trilio_backupplan_info{install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Helm",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(trilio_backupplan_info{applicationtype=\"Helm\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (applicationtype)",
     "legendFormat": "{{applicationtype}}"
    }
   ]
  },
  {
   "title": "Operator",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(trilio_backupplan_info{applicationtype=\"Operator\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (applicationtype)",
     "legendFormat": "{{applicationtype}}"
    }
   ]
  },
  {
   "title": "Custom",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(trilio_backupplan_info{applicationtype=\"Custom\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (applicationtype)",
     "legendFormat": "{{applicationtype}}"
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(trilio_backupplan_info{applicationtype=\"Namespace\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (applicationtype)",
     "legendFormat": "{{applicationtype}}"
    }
   ]
  },
  {
   "title": "Protected Backup Plan",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(trilio_backupplan_info{applicationtype=~\"$ApplicationType\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (protected)",
     "legendFormat": "{{protected}}"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 5 },
   "targets": [
    {
     "expr": "trilio_backupplan_info{applicationtype=~\"$ApplicationType\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  }
 ]
}