{
 "title": "Restore Overview",
 "tags": [ "logging" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "Cluster", "query": "trilio_system_info" },
   {
    "name": "Scope",
    "query": "trilio_system_info{cluster=~\"$Cluster\"}"
   },
   {
    "name": "Install_Namespace",
    "label": "Install Namespace",
    "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
   },
   { "name": "Status", "label": "status", "query": "trilio_restore_info" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 1, "y": 0 },
   "options": {
    "content": "<center><h1> Restores Overview </h1></center>"
   },
   "content": "<center><h1> Restores Overview </h1></center>"
  },
  {
   "title": "All",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "count(trilio_restore_info{install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) ",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(trilio_restore_info{status=\"Completed\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "InProgress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(trilio_restore_info{status=\"InProgress\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(trilio_restore_info{status=\"Failed\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "UnKnown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "count(trilio_restore_info{status=\"UnKnown\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "trilio_restore_status_percentage{status=~\"$Status\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  }
 ]
}