{
 "title": "Target Detail",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "loki datasource", "query": "loki" },
   { "name": "Cluster", "query": { "query": "trilio_system_info" } },
   {
    "name": "Scope",
    "query": {
     "query": "trilio_system_info{cluster=~\"$Cluster\"}"
    }
   },
   {
    "name": "Install_Namespace",
    "label": "Install Namespace",
    "query": {
     "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
    }
   },
   {
    "name": "Target",
    "label": "Target",
    "query": {
     "query": "trilio_target_info{cluster=~\"$Cluster\"}"
    }
   },
   {
    "name": "Resource_Namespace",
    "label": "Resource Namespace",
    "query": "label_values({transaction_type=\"Target\",transaction_resource_name=~\"$Target\"},transaction_resource_namespace)"
   },
   {
    "name": "transaction_id",
    "label": "Transaction ID",
    "query": "label_values({transaction_resource_name=~\"$Target\",transaction_type=\"Target\",transaction_resource_namespace=~\"$Resource_Namespace\"},transaction_id)"
   },
   {
    "name": "service_type",
    "label": "Service Type",
    "query": "label_values({transaction_type=\"Target\",transaction_id=~\"$transaction_id\"}, service_type)"
   },
   {
    "name": "service_id",
    "label": "Service ID",
    "query": "label_values({transaction_type=\"Target\",transaction_id=~\"$transaction_id\",service_type=~\"$service_type\"}, service_id)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>Targets</h1></center>"
   }
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "avg(trilio_target_info{target=~\"$Target\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Total Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(trilio_backup_storage{target=~\"$Target\",status=~\"Available\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Threshold Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_target_info{ target=~\"$Target\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Browsing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_target_info{ target=~\"$Target\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Vendor ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_target_info{ target=~\"$Target\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Vendor Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_target_info{ target=~\"$Target\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Creattion Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "trilio_target_info{ target=~\"$Target\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Backups",
   "type": "table-old",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "topk(10,trilio_backup_info{target=~\"$Target\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (size)",
     "legendFormat": "{{backup}} {{status}}"
    }
   ]
  },
  {
   "title": "Target Logs ",
   "type": "logs",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "{transaction_type=\"Target\",transaction_resource_name=~\"$Target\",transaction_id=~\"$transaction_id\",service_type=~\"$service_type\"}"
    }
   ]
  }
 ]
}