{{- if ((.Values.namespaced | default dict).enabled | default false) }}
{{- if .Values.namespaced.replayCoordinator.enabled }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
{{- with .Values.namespaced.image.pullSecrets }}
imagePullSecrets: {{ toYaml . | nindent 2 }}
{{- end }}
metadata:
  name: speedscale-replay-coordinator
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- with .Values.namespaced.globalLabels }}
{{ toYaml . | indent 4 }}
    {{- end }}
    app: speedscale-replay-coordinator
    controlplane.speedscale.com/component: replay-coordinator
  {{- with .Values.namespaced.globalAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- end }}
