{{- if ((.Values.namespaced | default dict).enabled | default false) }}
{{- if and (eq .Values.namespaced.forwarder.primaryTransport "cloud") .Values.namespaced.inspector.enabled (not .Values.namespaced.forwarder.enabled) -}}
{{- fail "cloud inspector transport requires forwarder.enabled=true" -}}
{{- end -}}

{{- end }}
