{
 "title": "K10 Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster" },
   { "name": "operation", "label": "operation", "query": { "query": "limiter_pending_count" } }
  ]
 },
 "panels": [
  {
   "title": "K10 System Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "K10 CPU total seconds ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[5m]))",
     "legendFormat": "Total CPU seconds"
    }
   ]
  },
  {
   "title": "K10 total memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes)",
     "legendFormat": "Total memory consumption"
    }
   ]
  },
  {
   "title": "CPU total seconds per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"httpServiceDiscovery\"}[5m])",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"k10-pods\"}[5m]))",
     "legendFormat": "executor"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"pushAggregator\"}[5m]))",
     "legendFormat": "ephemeral pods"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"prometheus\"}[5m]))",
     "legendFormat": "prometheus"
    }
   ]
  },
  {
   "title": "Memory consumption by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"pushAggregator\"}",
     "legendFormat": "ephemeral pods"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"httpServiceDiscovery\"}",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"k10-pods\"})",
     "legendFormat": "executor"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"prometheus\"})",
     "legendFormat": "prometheus"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backups Completed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_ended_overall{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Backups Failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_ended_overall{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Backups Skipped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_skipped_overall{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Restores Completed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_ended_overall{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Restores Failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_ended_overall{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Restores Skipped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_skipped_overall{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Backups Completed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_cluster_ended_overall{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster Backups Failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_cluster_ended_overall{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster Backups Skipped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_backup_cluster_skipped_overall{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster Restores Completed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_cluster_ended_overall{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster Restores Failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_cluster_ended_overall{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Cluster Restores Skipped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_restore_cluster_skipped_overall{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Backup Exports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Exports Completed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_export_ended_overall{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Exports Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_export_ended_overall{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Exports Skipped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_export_skipped_overall{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Imports Completed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_import_ended_overall{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Imports Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_import_ended_overall{cluster=\"$cluster\", state=~\"failed|cancelled\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Imports Skipped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_import_skipped_overall{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Policy Runs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "runs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_run_ended_overall{cluster=\"$cluster\", state=\"succeeded\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Policy Runs Skipped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "runs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(action_run_skipped_overall{cluster=\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Catalog Volume Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "catalog_persistent_volume_disk_space_used_bytes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Catalog Volume Used Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-catalog_persistent_volume_free_space_percent{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Jobs Volume Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_persistent_volume_disk_space_used_bytes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Jobs Volume Used Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-jobs_persistent_volume_free_space_percent{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Logging Volume Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logging_persistent_volume_disk_space_used_bytes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Logging Volume Used Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-logging_persistent_volume_free_space_percent{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Compliant Applications",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "compliance_count{state=\"Compliant\"}"
    }
   ]
  },
  {
   "title": "Non-Compliant Applications",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "compliance_count{state=\"NotCompliant\"}"
    }
   ]
  },
  {
   "title": "Unmanaged Applications",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "compliance_count{state=\"Unmanaged\"}"
    }
   ]
  },
  {
   "title": "Snapshot Size (Physical)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snapshot_storage_size_bytes{cluster=\"$cluster\", type=\"physical\"}"
    }
   ]
  },
  {
   "title": "Snapshot Size (Logical)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snapshot_storage_size_bytes{cluster=\"$cluster\", type=\"logical\"}"
    }
   ]
  },
  {
   "title": "Export Size (Physical)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "export_storage_size_bytes{cluster=\"$cluster\", type=\"physical\"}"
    }
   ]
  },
  {
   "title": "Export Size (Logical)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "export_storage_size_bytes{cluster=\"$cluster\", type=\"logical\"}"
    }
   ]
  },
  {
   "title": "Execution Control",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Executor Worker Load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "sum(exec_executor_worker_count)",
       "legendFormat": "Worker Count"
      },
      {
       "expr": "sum(exec_active_job_count) OR on() vector(0)",
       "legendFormat": "Worker Load"
      }
     ]
    },
    {
     "title": "Average Action Duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(action_backup_duration_seconds_sum_overall[5m])) / sum(rate(action_backup_ended_overall[5m]))",
       "legendFormat": "Backup"
      },
      {
       "expr": "sum(rate(action_backup_cluster_duration_seconds_overall_sum[5m])) / sum(rate(action_backup_cluster_ended_overall[5m]))",
       "legendFormat": "Backup Cluster"
      },
      {
       "expr": "sum(rate(action_export_duration_seconds_sum_overall[5m])) / sum(rate(action_export_ended_overall[5m]))",
       "legendFormat": "Export"
      },
      {
       "expr": "sum(rate(action_import_duration_seconds_sum_overall[5m])) / sum(rate(action_import_ended_overall[5m]))",
       "legendFormat": "Import"
      },
      {
       "expr": "sum(rate(action_report_duration_seconds_sum_overall[5m])) / sum(rate(action_report_ended_overall[5m]))",
       "legendFormat": "Report"
      },
      {
       "expr": "sum(rate(action_retire_duration_seconds_sum_overall[5m])) / sum(rate(action_retire_ended_overall[5m]))",
       "legendFormat": "Retire"
      },
      {
       "expr": "sum(rate(action_restore_duration_seconds_sum_overall[5m])) / sum(rate(action_restore_ended_overall[5m]))",
       "legendFormat": "Restore"
      },
      {
       "expr": "sum(rate(action_restore_cluster_duration_seconds_sum_overall[5m])) / sum(rate(action_restore_cluster_ended_overall[5m]))",
       "legendFormat": "Restore Cluster"
      }
     ]
    },
    {
     "title": "Finished Backups",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(round(increase(action_backup_ended_overall[1m:10s]))) by (state)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Finished Cluster Backups",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(round(increase(action_backup_cluster_ended_overall[1m:10s]))) by (state)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Finished Exports",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(round(increase(action_export_ended_overall[1m:10s]))) by (state)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Finished Imports",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(round(increase(action_import_ended_overall[1m:10s]))) by (state)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Finished Reports",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(round(increase(action_report_ended_overall[1m:10s]))) by (state)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Finished Retires",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(round(increase(action_retire_ended_overall[1m:10s]))) by (state)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Finished Restores",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(round(increase(action_restore_ended_overall[1m:10s]))) by (state)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Finished Cluster Restores",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(round(increase(action_restore_cluster_ended_overall[1m:10s]))) by (state)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate Limiter - avg operation duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(limiter_request_seconds_sum{stage=\"hold\"}[5m])) by (operation) / sum(rate(limiter_request_seconds_count{stage=\"hold\"}[5m])) by (operation) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate Limiter - $operation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4.8, "x": 0, "y": 82 },
     "repeat": "operation",
     "targets": [
      {
       "expr": "limiter_inflight_count{operation=\"$operation\"}",
       "legendFormat": "Inflight"
      },
      {
       "expr": "limiter_pending_count{operation=\"$operation\"}",
       "legendFormat": "Pending"
      },
      {
       "expr": "limiter_inflight_limit_value{operation=\"$operation\"}",
       "legendFormat": "Limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Data reduction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transferred/Processed Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(action_export_transferred_bytes[5m:30s]))/sum((increase(action_export_processed_bytes[5m:30s])>0))",
       "legendFormat": "Transferred/Processed across all actions"
      }
     ]
    },
    {
     "title": "Transferred/Processed Ratio per policy:app",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(increase(action_export_transferred_bytes[5m:30s])/(increase(action_export_processed_bytes[5m:30s])>0))",
       "legendFormat": "{{policy}}:{{app}}"
      }
     ]
    },
    {
     "title": "Transferred bytes per policy:app",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(action_export_transferred_bytes[5m:30s]) > 0",
       "legendFormat": "{{policy}}:{{app}}"
      }
     ]
    },
    {
     "title": "Processed bytes per policy:app",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(action_export_processed_bytes[5m:30s]) > 0",
       "legendFormat": "{{policy}}:{{app}}"
      }
     ]
    }
   ]
  }
 ]
}