{{/* AUTOGENERATED FILE DO NOT EDIT */}}

{{/*
Operator mutating webhooks
*/}}
{{- define "airlock-microgateway-operator.mutatingWebhooks" -}}
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-v1-pod
  failurePolicy: Fail
  name: mutate-pod.microgateway.airlock.com
  reinvocationPolicy: IfNeeded
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      operations:
        - CREATE
      resources:
        - pods
  sideEffects: None
  objectSelector:
    matchLabels:
      sidecar.microgateway.airlock.com/inject: "true"
{{- end }}

{{/*
Operator validating webhooks
*/}}
{{- define "airlock-microgateway-operator.validatingWebhooks" -}}
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-accesscontrol
  failurePolicy: Fail
  name: validate-accesscontrol.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - accesscontrols
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-accesscontrolpolicy
  failurePolicy: Fail
  name: validate-accesscontrolpolicy.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - accesscontrolpolicies
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-apiprotection
  failurePolicy: Fail
  name: validate-apiprotection.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - apiprotections
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-contentsecurity
  failurePolicy: Fail
  name: validate-contentsecurity.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - contentsecurities
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-contentsecuritypolicy
  failurePolicy: Fail
  name: validate-contentsecuritypolicy.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - contentsecuritypolicies
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-csrfprotection
  failurePolicy: Fail
  name: validate-csrfprotection.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - csrfprotections
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-denyrules
  failurePolicy: Fail
  name: validate-denyrules.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - denyrules
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-envoycluster
  failurePolicy: Fail
  name: validate-envoycluster.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - envoyclusters
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-envoyhttpfilter
  failurePolicy: Fail
  name: validate-envoyhttpfilter.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - envoyhttpfilters
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-gatewayparameters
  failurePolicy: Fail
  name: validate-gatewayparameters.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - gatewayparameters
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-graphql
  failurePolicy: Fail
  name: validate-graphql.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - graphqls
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-headerrewrites
  failurePolicy: Fail
  name: validate-headerrewrites.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - headerrewrites
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-identitypropagation
  failurePolicy: Fail
  name: validate-identitypropagation.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - identitypropagations
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-jwks
  failurePolicy: Fail
  name: validate-jwks.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - jwks
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-jwt
  failurePolicy: Fail
  name: validate-jwt.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - jwts
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-limits
  failurePolicy: Fail
  name: validate-limits.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - limits
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-oidcprovider
  failurePolicy: Fail
  name: validate-oidcprovider.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - oidcproviders
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-oidcrelyingparty
  failurePolicy: Fail
  name: validate-oidcrelyingparty.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - oidcrelyingparties
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-openapi
  failurePolicy: Fail
  name: validate-openapi.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - openapis
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-parser
  failurePolicy: Fail
  name: validate-parser.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - parsers
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-redisprovider
  failurePolicy: Fail
  name: validate-redisprovider.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - redisproviders
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-sessionhandling
  failurePolicy: Fail
  name: validate-sessionhandling.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - sessionhandlings
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-sidecargateway
  failurePolicy: Fail
  name: validate-sidecargateway.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - sidecargateways
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-microgateway-airlock-com-v1alpha1-tokenexchange
  failurePolicy: Fail
  name: validate-tokenexchange.microgateway.airlock.com
  rules:
    - apiGroups:
        - microgateway.airlock.com
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - tokenexchanges
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: airlock-microgateway-operator-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-v1-pod
  failurePolicy: Fail
  name: validate-pod.microgateway.airlock.com
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      operations:
        - CREATE
        - UPDATE
      resources:
        - pods
  sideEffects: None
  objectSelector:
    matchLabels:
      sidecar.microgateway.airlock.com/inject: "true"
{{- end }}
