{
 "title": "PolicyReports Compliance Dashboard",
 "tags": [ "Policy Reporter" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "policy",
    "label": "Policy",
    "query": {
     "query": "label_values({__name__=~ \"policy_report_result|cluster_policy_report_result\", status=~\"fail|error\"}, policy)"
    }
   },
   {
    "name": "category",
    "label": "Category",
    "query": {
     "query": "label_values({__name__=~ \"policy_report_result|cluster_policy_report_result\", status=~\"fail|error\"}, category)"
    }
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": {
     "query": "label_values({__name__=~ \"policy_report_result|cluster_policy_report_result\", status=~\"fail|error\"}, severity)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values({__name__= \"policy_report_result\", status=~\"fail|error\"}, namespace)"
    }
   },
   {
    "name": "kind",
    "label": "Kind",
    "query": {
     "query": "label_values({__name__=~ \"policy_report_result|cluster_policy_report_result\", status=~\"fail|error\"}, kind)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values({__name__=~ \"policy_report_result|cluster_policy_report_result\", status=~\"fail|error\"}, source)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Compliance Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PSS Baseline",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (sum(policy_report:results:sum{policy=~\"$policy\", category=\"Pod Security Standards (Baseline)\", severity=~\"$severity\", kind=~\"$kind\",  namespace=~\"$namespace\", status=\"pass\"})  or vector(0))\n  + (sum(cluster_policy_report:results:sum{policy=~\"$policy\", category=\"Pod Security Standards (Baseline)\", severity=~\"$severity\", kind=~\"$kind\", status=\"pass\"}) or vector(0))\n) \n/ \n(\n  (sum(policy_report:results_total:sum{policy=~\"$policy\", category=\"Pod Security Standards (Baseline)\", severity=~\"$severity\", kind=~\"$kind\",  namespace=~\"$namespace\"}) or vector(0))\n  + \n  (sum(cluster_policy_report:results_total:sum{policy=~\"$policy\", category=\"Pod Security Standards (Baseline)\", severity=~\"$severity\", kind=~\"$kind\"}) or vector(0))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSS Restricted",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (sum(policy_report:results:sum{policy=~\"$policy\", category=\"Pod Security Standards (Restricted)\", severity=~\"$severity\", kind=~\"$kind\",  namespace=~\"$namespace\", status=\"pass\"})  or vector(0))\n  + (sum(cluster_policy_report:results:sum{policy=~\"$policy\", category=\"Pod Security Standards (Restricted)\", severity=~\"$severity\", kind=~\"$kind\", status=\"pass\"}) or vector(0))\n) \n/ \n(\n  (sum(policy_report:results_total:sum{policy=~\"$policy\", category=\"Pod Security Standards (Restricted)\", severity=~\"$severity\", kind=~\"$kind\",  namespace=~\"$namespace\"}) or vector(0))\n  + \n  (sum(cluster_policy_report:results_total:sum{policy=~\"$policy\", category=\"Pod Security Standards (Restricted)\", severity=~\"$severity\", kind=~\"$kind\"}) or vector(0))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RBAC Best Practices",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n(sum(policy_report:results:sum{policy=~\"$policy\", category=\"RBAC Best Practices\", severity=~\"$severity\", kind=~\"$kind\", namespace=~\"$namespace\", status=\"pass\"}) or vector(0))\n+ (sum(cluster_policy_report:results:sum{policy=~\"$policy\", category=\"RBAC Best Practices\", severity=~\"$severity\", kind=~\"$kind\", status=\"pass\"}) or vector(0))\n)\n/\n(\n(sum(policy_report:results_total:sum{policy=~\"$policy\", category=\"RBAC Best Practices\", severity=~\"$severity\", kind=~\"$kind\", namespace=~\"$namespace\"}) or vector(0))\n+\n(sum(cluster_policy_report:results_total:sum{policy=~\"$policy\", category=\"RBAC Best Practices\", severity=~\"$severity\", kind=~\"$kind\"}) or vector(0))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSS (Baseline) - Compliance over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  (sum(policy_report:results:sum{policy=~\"$policy\", category=\"Pod Security Standards (Baseline)\", severity=~\"$severity\", kind=~\"$kind\",  namespace=~\"$namespace\", status=\"pass\"})  or vector(0))\n  + (sum(cluster_policy_report:results:sum{policy=~\"$policy\", category=\"Pod Security Standards (Baseline)\", severity=~\"$severity\", kind=~\"$kind\", status=\"pass\"}) or vector(0))\n) \n/ \n(\n  (sum(policy_report:results_total:sum{policy=~\"$policy\", category=\"Pod Security Standards (Baseline)\", severity=~\"$severity\", kind=~\"$kind\",  namespace=~\"$namespace\"}) or vector(0))\n  + \n  (sum(cluster_policy_report:results_total:sum{policy=~\"$policy\", category=\"Pod Security Standards (Baseline)\", severity=~\"$severity\", kind=~\"$kind\"}) or vector(0))\n) * 100",
     "legendFormat": "Compliance"
    }
   ]
  },
  {
   "title": "PSS (Restricted) - Compliance over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  (sum(policy_report:results:sum{policy=~\"$policy\", category=\"Pod Security Standards (Restricted)\", severity=~\"$severity\", kind=~\"$kind\",  namespace=~\"$namespace\", status=\"pass\"})  or vector(0))\n  + (sum(cluster_policy_report:results:sum{policy=~\"$policy\", category=\"Pod Security Standards (Restricted)\", severity=~\"$severity\", kind=~\"$kind\", status=\"pass\"}) or vector(0))\n) \n/ \n(\n  (sum(policy_report:results_total:sum{policy=~\"$policy\", category=\"Pod Security Standards (Restricted)\", severity=~\"$severity\", kind=~\"$kind\",  namespace=~\"$namespace\"}) or vector(0))\n  + \n  (sum(cluster_policy_report:results_total:sum{policy=~\"$policy\", category=\"Pod Security Standards (Restricted)\", severity=~\"$severity\", kind=~\"$kind\"}) or vector(0))\n) * 100",
     "legendFormat": "Compliance"
    }
   ]
  },
  {
   "title": "RBAC Best Practices - Compliance over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  (sum(policy_report:results:sum{policy=~\"$policy\", category=\"RBAC Best Practices\", severity=~\"$severity\", kind=~\"$kind\",  namespace=~\"$namespace\", status=\"pass\"})  or vector(0))\n  + (sum(cluster_policy_report:results:sum{policy=~\"$policy\", category=\"RBAC Best Practices\", severity=~\"$severity\", kind=~\"$kind\", status=\"pass\"}) or vector(0))\n) \n/ \n(\n  (sum(policy_report:results_total:sum{policy=~\"$policy\", category=\"RBAC Best Practices\", severity=~\"$severity\", kind=~\"$kind\",  namespace=~\"$namespace\"}) or vector(0))\n  + \n  (sum(cluster_policy_report:results_total:sum{policy=~\"$policy\", category=\"RBAC Best Practices\", severity=~\"$severity\", kind=~\"$kind\"}) or vector(0))\n) * 100",
     "legendFormat": "Compliance"
    }
   ]
  },
  {
   "title": "Total Policy Violations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", namespace=~\"$namespace\", status=\"fail\" })",
     "legendFormat": "Violations"
    }
   ]
  },
  {
   "title": "Policy Violations by Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", namespace=~\"$namespace\" }) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Policy Violations by Category",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", namespace=~\"$namespace\" , status=\"fail\"}) by (category)",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Policy Violations by Kind",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", namespace=~\"$namespace\" , status=\"fail\"}) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Policy Violations by Severity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", namespace=~\"$namespace\" , status=\"fail\"}) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  { "title": "Policies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Failing PolicyRules",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "max(sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", namespace=~\"$namespace\", status=~\"fail|error\" }) by (pod,namespace,policy,rule,kind,name,status,category,severity,source)) by (namespace,policy,rule,kind,name,status,category,severity,source)",
     "legendFormat": "{{namespace}}: {{ policy }}"
    }
   ]
  },
  {
   "title": "Failing ClusterPolicyRules",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "max(sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", source=~\"$source\", kind=~\"$kind\", status=~\"fail|error\" })by (pod,policy,rule,kind,name,status,category,severity,source)) by (policy,rule,kind,name,status,category,severity,source)",
     "legendFormat": "{{ kind }}: {{ name }} - {{ policy }}"
    }
   ]
  }
 ]
}