annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: |
        chore: bump openbao to v2.5.3
    - kind: changed
      description: |
        chore: bump openbao-csi-provider to v2.0.2
  artifacthub.io/containsSecurityUpdates: "true"
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: OpenBao
  catalog.cattle.io/kube-version: '>= 1.30.0-0'
  catalog.cattle.io/release-name: openbao
  charts.openshift.io/name: Openbao
apiVersion: v2
appVersion: v2.5.3
description: Official OpenBao Chart
home: https://github.com/openbao/openbao-helm
icon: file://assets/icons/openbao.svg
keywords:
- vault
- openbao
- security
- encryption
- secrets
- management
- automation
- infrastructure
kubeVersion: '>= 1.30.0-0'
maintainers:
- email: openbao-security@lists.openssf.org
  name: OpenBao
  url: https://openbao.org
name: openbao
sources:
- https://github.com/openbao/openbao-helm
version: 0.27.2
