apiVersion: v1
data:
  svc-key.pem: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0
    NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ1FlNGVzaFVoaFRiNlZhM2UKbGZmajBuMDJNVDhG
    cUZ0TnZNSWZSMmVMdFlxaFJBTkNBQVJxaENIYVUyWm4zaG1FT1dTanlpeXViTy92Yy9ITg
    ptVWVCQ2RyL2FBUTB4bWQ0TVlmM1JqMWIrYm9EUFIyRDdZejNrazdGSkRJZ2R3VzRIby9O
    cldWcAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t
  svc.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNuakNDQWtXZ0F3SUJBZ0lSQU9zYW
    Jvemplak5DaUNweGpiS2VFNjR3Q2dZSUtvWkl6ajBFQXdRd1BqRVQKTUJFR0ExVUVCeE1L
    UzNWaVpYSnVaWFJsY3pFTU1Bb0dBMVVFQmhNRFJFVldNUmt3RndZRFZRUURFeEJQY0dWeQ
    pZWFJ2Y2lCU2IyOTBJRU5CTUI0WERUSTFNVEV4T0RBd01EQXdNRm9YRFRNd01URXhPREF3
    TURBd01Gb3dQakVUCk1CRUdBMVVFQnhNS1MzVmlaWEp1WlhSbGN6RU1NQW9HQTFVRUJoTU
    RSRVZXTVJrd0Z3WURWUVFERXhCUGNHVnkKWVhSdmNpQlRaWEoyYVdObE1Ga3dFd1lIS29a
    SXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWFvUWgybE5tWjk0WgpoRGxrbzhvc3JtenY3M1
    B4elpsSGdRbmEvMmdFTk1abmVER0g5MFk5Vy9tNkF6MGRnKzJNOTVKT3hTUXlJSGNGCnVC
    NlB6YTFsYWFPQ0FTSXdnZ0VlTUFrR0ExVWRFd1FDTUFBd0RnWURWUjBQQVFIL0JBUURBZ1
    hnTUIwR0ExVWQKSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFkQmdOVkhR
    NEVGZ1FVQUsrWXZOMkVsMWs2VEg1UQpZT0tYazloNjZxOHdiUVlEVlIwakJHWXdaSUFVQU
    srWXZOMkVsMWs2VEg1UVlPS1hrOWg2NnEraFFxUkFNRDR4CkV6QVJCZ05WQkFjVENrdDFZ
    bVZ5Ym1WMFpYTXhEREFLQmdOVkJBWVRBMFJGVmpFWk1CY0dBMVVFQXhNUVQzQmwKY21GMG
    IzSWdVbTl2ZENCRFFZSUlDeVlTdTJXMzV5OHdWQVlEVlIwUkJFMHdTNEltWkhodmNHVnlZ
    WFJ2Y2kxMgpNaTVrZUc5d1pYSmhkRzl5TFhZeUxYTjVjM1JsYlM1emRtT0NHaW91Wkhodm
    NHVnlZWFJ2Y2kxMk1pMXplWE4wClpXMHVjM1pqZ2dVcUxuTjJZekFLQmdncWhrak9QUVFE
    QkFOSEFEQkVBaUFmRytIZktjWUVSbFJoT0JtSXAwVDgKZHZ3QVZwSysyS3A5VlpORzBkZE
    1sd0lnWEFEOHJzL1pDLzd5aFZKckxwNGVNRUY5WHkydWZ5NHVOMDgvYkVHaQpyeFU9Ci0t
    LS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
kind: Secret
metadata:
  labels:
    operator: dxoperator-v2
  name: dxoperator-v2-webhook-cert-t84khh44kt
  namespace: dxoperator-v2-system
type: Opaque
