annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: DevGuard
  catalog.cattle.io/kube-version: '>=1.21-0'
  catalog.cattle.io/release-name: devguard
apiVersion: v2
appVersion: v1.7.0
description: A Helm chart for DevGuard
icon: file://assets/icons/devguard.png
kubeVersion: '>=1.21-0'
name: devguard
type: application
version: 1.7.0
