{{- if and .Values.tls.enabled (not .Values.tls.certManager.enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-perf-advisor-tls-pem
  namespace: {{ include "perf-advisor-chart.namespace" . }}
  labels:
    app: "{{ template "perf-advisor-chart.name" . }}"
    chart: "{{ template "perf-advisor-chart.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- if .Values.commonLabels }}
  {{ include "perf-advisor-chart.commonLabels" . | indent 4 }}
  {{- end }}
type: Opaque
data:
  {{- include "getOrCreateServerPem" (dict "Namespace" (include "perf-advisor-chart.namespace" .) "Root" . "Name" (printf "%s%s" .Release.Name "-perf-advisor-tls-pem")) | nindent 2 }}
{{- end }}
{{- if .Values.tls.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-perf-advisor-export-certs
  namespace: {{ include "perf-advisor-chart.namespace" . }}
  labels:
    app: {{ .Release.Name }}-perf-advisor
    chart: {{ include "perf-advisor-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service | quote }}
  {{- if .Values.commonLabels }}
  {{ include "perf-advisor-chart.commonLabels" . | indent 4 }}
  {{- end }}
data:
  export-certs.sh: |
    #!/bin/bash
    set -x -o errexit

    rm -f /opt/yugabyte/perf-advisor/certs/tls.p12

    openssl pkcs12 -export -inkey /opt/yugabyte/perf-advisor/pem-certs/tls.key \
    -in /opt/yugabyte/perf-advisor/pem-certs/tls.crt \
    -out /opt/yugabyte/perf-advisor/certs/tls.p12 \
    -password pass:${KEYSTORE_PASSWORD}
{{- end }}