apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-perf-advisor-secret
  namespace: {{ include "perf-advisor-chart.namespace" . }}
  labels:
    app: {{ .Release.Name }}-perf-advisor
    chart: {{ include "perf-advisor-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.commonLabels }}
{{ include "perf-advisor-chart.commonLabels" . | indent 4 }}
{{- end }}
type: Opaque
data:
  # quote - makes single quote
  PA_API_TOKEN: {{ include "perf-advisor-chart.getOrGeneratePassword" (dict "Namespace" (include "perf-advisor-chart.namespace" .) "Name" (printf "%s-perf-advisor-secret" .Release.Name) "Key" "PA_API_TOKEN" "Length" 64 "UserValue" .Values.perfAdvisor.api.token) | quote }}
{{- if (.Values.tls.enabled) }}
  KEYSTORE_PASSWORD: {{ include "perf-advisor-chart.getOrGeneratePassword" (dict "Namespace" (include "perf-advisor-chart.namespace" .) "Name" (printf "%s-perf-advisor-secret" .Release.Name) "Key" "KEYSTORE_PASSWORD" "Length" 64 "UserValue" .Values.tls.perfAdvisor.keystore.password) | quote }}
{{- end }}