{{- if .Values.perfAdvisor.collector.topology }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-perf-advisor-collector-topology
  namespace: {{ include "perf-advisor-chart.namespace" . }}
  labels:
    app: {{ .Release.Name }}-perf-advisor
    chart: {{ include "perf-advisor-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.commonLabels }}
{{ include "perf-advisor-chart.commonLabels" . | indent 4 }}
{{- end }}
data:
  collectors.yml: |-
  {{ toYaml .Values.perfAdvisor.collector.topology | nindent 4 }}
{{- end }}
