{{- if and (not .Values.postgres.external.host) (not .Values.yugaware.enabled) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-postgres-pv-claim
  namespace: {{ include "perf-advisor-chart.namespace" . }}
  labels:
    app: {{ .Release.Name }}-postgres
    chart: {{ include "perf-advisor-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.commonLabels }}
{{ include "perf-advisor-chart.commonLabels" . | indent 4 }}
{{- end }}
spec:
  {{- with .Values.postgres.pvc.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storage }}
{{- end }}
