{{- if and (not .Values.prometheus.external.url) (not .Values.yugaware.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
  namespace: {{ include "perf-advisor-chart.namespace" . }}
  labels:
    app: {{ .Release.Name }}-prometheus
    chart: {{ include "perf-advisor-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.commonLabels }}
{{ include "perf-advisor-chart.commonLabels" . | indent 4 }}
{{- end }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-prometheus
  ports:
    - name: http
      port: {{ .Values.prometheus.port }}
      targetPort: {{ .Values.prometheus.port }}
{{- end }}
