annotations:
  charts.openshift.io/name: kubedb-kubestash-catalog
apiVersion: v2
appVersion: v2026.4.27
description: KubeStash Catalog by AppsCode - Catalog of KubeStash Addons
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
kubeVersion: '>=1.28.0-0'
maintainers:
- email: support@appscode.com
  name: appscode
name: kubedb-kubestash-catalog
sources:
- https://github.com/kuebstash
type: application
version: v2026.4.27
