annotations:
  charts.openshift.io/name: storage-metrics-server
apiVersion: v1
appVersion: v0.1.0
description: Kubernetes Storage Metrics API server by AppsCode
home: https://github.com/kubeops/storage-metrics-server
icon: https://cdn.appscode.com/images/products/bytebuilders/bytebuilders-512x512.png
keywords:
- kubernetes
- metrics
- autoscaling
- storage
- pvc
kubeVersion: '>=1.26.0-0'
maintainers:
- email: support@appscode.com
  name: appscode
name: storage-metrics-server
sources:
- https://github.com/kubeops/storage-metrics-server
version: v0.1.0
