project:
  name: Kubernetes Storage Metrics API Server by AppsCode
  shortName: Storage Metrics API Server
  url: https://github.com/kubeops/storage-metrics-server
  description: Kubernetes Storage Metrics API server by AppsCode
  app: Storage Metrics API server
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: storage-metrics-server
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.26+
release:
  name: storage-metrics-server
  namespace: kubeops
