apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nsgcconfigmap.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  LOGLEVEL: {{ .Values.gatewayController.logLevel | quote | lower }}
  JSONLOG: {{ .Values.gatewayController.jsonLog | quote | lower }}
  NS_PROTOCOL: {{ .Values.netscaler.nsProtocol | quote | lower }}
  NS_PORT: {{ .Values.netscaler.nsPort | quote }}
{{- if .Values.netscaler.podIPsforServiceGroupMembers }}
  POD_IPS_FOR_SERVICEGROUP_MEMBERS: {{ .Values.netscaler.podIPsforServiceGroupMembers | quote }}
{{- end }}
{{- if .Values.netscaler.nsSNIPs }}
  NS_SNIPS: {{ .Values.netscaler.nsSNIPs | toJson | quote }}
{{- end }}
{{- if .Values.netscaler.ignoreNodeExternalIP }}
  IGNORE_NODE_EXTERNAL_IP: {{ .Values.netscaler.ignoreNodeExternalIP | quote }}
{{- end }}

{{- if .Values.gatewayController.analyticsConfig.required }}
  NS_ANALYTICS_CONFIG: |
    logAllJsonFields: {{ .Values.gatewayController.analyticsConfig.logAllJsonFields | quote }}
    distributed_tracing:
      enable: {{ .Values.gatewayController.analyticsConfig.distributedTracing.enable | quote }}
      samplingrate: {{ .Values.gatewayController.analyticsConfig.distributedTracing.samplingrate }}
    splunk:
      enable: {{ .Values.gatewayController.analyticsConfig.splunk.enable | quote }}
      {{- with .Values.gatewayController.analyticsConfig.splunk.servers }}
      servers:
        {{- $filteredServers := list }}
        {{- range $server := . }}
          {{- $filteredProfiles := dict }}
          {{- range $profileType, $profileParams := (default dict $server.profiles) }}
            {{- if $profileParams }}
              {{- $_ := set $filteredProfiles $profileType $profileParams }}
            {{- end }}
          {{- end }}
          {{- $filteredServer := omit $server "profiles" }}
          {{- if $filteredProfiles }}
            {{- $filteredServer = set $filteredServer "profiles" $filteredProfiles }}
          {{- end }}
          {{- $filteredServers = append $filteredServers $filteredServer }}
        {{- end }}
        {{- toYaml $filteredServers | nindent 8 }}
      {{- end }}
{{- end }}

