apiVersion: v2
appVersion: v2.0.0
description: Kyverno extension service for Notation and the AWS signer
keywords:
- kubernetes
- nirmata
- AWS signer
- notation
maintainers:
- email: support@nirmata.com
  name: Nirmata
  url: https://nirmata.com/
name: kyverno-notation-aws
type: application
version: 2.0.0
