{
 "title": "Metadata Detail",
 "tags": [ "monitoring" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "Cluster", "query": "trilio_system_info" },
   {
    "name": "Scope",
    "query": "trilio_system_info{cluster=~\"$Cluster\"}"
   },
   {
    "name": "Install_Namespace",
    "label": "Install Namespace",
    "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
   },
   {
    "name": "Backup",
    "label": "Backup",
    "query": "trilio_backup_info{cluster=~\"$Cluster\",install_namespace=~\"$Install_Namespace\"}"
   },
   {
    "name": "Restore",
    "label": "Restore",
    "query": "trilio_restore_info{cluster=~\"$Cluster\",install_namespace=~\"$Install_Namespace\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>Backup Metatdata</h1></center>"
   },
   "content": "<center><h1>Backup Metatdata</h1></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<center><h1>Restore Metatdata</h1></center>"
   },
   "content": "<center><h1>Restore Metatdata</h1></center>"
  },
  {
   "title": "Total Component Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "count(avg(trilio_backup_metadata_info{backup=~\"$Backup\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (objecttype))"
    }
   ]
  },
  {
   "title": "Total Components",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "count(avg(trilio_backup_metadata_info{backup=~\"$Backup\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (objectname))"
    }
   ]
  },
  {
   "title": "Total Component Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "count(avg(trilio_restore_metadata_info{restore=~\"$Restore\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (objecttype))"
    }
   ]
  },
  {
   "title": "Total Components",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "count(avg(trilio_restore_metadata_info{restore=~\"$Restore\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (objectname))"
    }
   ]
  },
  {
   "title": "Metadata Info",
   "type": "table-old",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg(trilio_backup_metadata_info{backup=~\"$Backup\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (objectname,objecttype, apiversion)"
    }
   ]
  },
  {
   "title": "Metadata Info",
   "type": "table-old",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "avg(trilio_restore_metadata_info{restore=~\"$Restore\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (objectname,objecttype, apiversion)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "trilio_backup_info{backup=~\"$Backup\",namespace=~\"$Namespace\",cluster=~\"$Cluster\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}