# https://hub.docker.com/r/rancher/rancher/tags
# https://github.com/rancher/rancher/releases

services:
  rancher:
    image: rancher/rancher:v2.14.2
    privileged: true
    restart: unless-stopped
    volumes:
      - ./data/auditlog:/var/log/auditlog
      - ./data/rancher:/var/lib/rancher
      # - ./data/rancher-data:/var/lib/rancher-data
    ports:
      - "8443:443"
