{{- if .Values.epinioUI.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: epinio-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: epinio-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.epinioUI.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: epinio-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: ui
    port: {{ .Values.epinioUI.service.port | default 80 }}
    targetPort: {{ .Values.epinioUI.service.containerPort | default 8000 }}
{{- end }}
