annotations:
  charts.openshift.io/name: kubedb-gitops
apiVersion: v2
appVersion: v0.12.0
description: KubeDB GitOps operator by AppsCode
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
kubeVersion: '>=1.28.0-0'
maintainers:
- email: support@appscode.com
  name: appscode
name: kubedb-gitops
sources:
- https://github.com/kubedb/gitops
type: application
version: v0.12.0
