{{- if .Values.gateway.caCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gateway-ca-cert
  namespace: {{ .Release.Namespace }}
data:
  ca.crt: {{ .Values.gateway.caCert }}
{{- end }}
