annotations:
  artifacthub.io/links: |
    - name: EULA
      url: https://nirmata.com/eula/
apiVersion: v2
appVersion: v0.3.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 13.4.1
- condition: openreports.enabled
  name: openreports
  repository: oci://ghcr.io/openreports/charts
  version: 0.2.1
home: https://nirmata.com/
keywords:
- kubernetes
- policy reports storage
- postgresql
kubeVersion: '>=1.16.0-0'
maintainers:
- email: support@nirmata.com
  name: Nirmata
  url: https://nirmata.com/
name: reports-server
sources:
- https://github.com/nirmata/reports-server
type: application
version: 0.3.0-rc4
