annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: "false"
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Epinio
  catalog.cattle.io/kube-version: '>=1.21-0'
  catalog.cattle.io/release-name: epinio
apiVersion: v2
appVersion: v1.12.0
dependencies:
- condition: global.dex.enabled
  name: dex
  repository: https://charts.dexidp.io
  tags:
  - dex
  version: 0.15.2
- condition: minio.enabled, global.minio.enabled
  name: minio
  repository: https://charts.min.io/
  tags:
  - minio
  version: 5.0.13
- condition: kubed.enabled, global.kubed.enabled
  name: kubed
  repository: https://charts.appscode.com/stable/
  tags:
  - kubed
  version: v0.13.2
- condition: s3gw.enabled, global.s3gw.enabled
  name: s3gw
  repository: https://s3gw-tech.github.io/s3gw-charts
  tags:
  - s3gw
  version: 0.14.0
description: Epinio deploys Kubernetes applications directly from source code in one
  step.
home: https://github.com/epinio/epinio
icon: file://assets/icons/epinio.png
keywords:
- epinio
- paas
kubeVersion: '>=1.21-0'
maintainers:
- email: epinio@krum.io
  name: Krumware
- email: epinio@epinio.io
  name: SUSE
name: epinio
sources:
- https://github.com/epinio/epinio
version: 1.12.0
