{
 "title": "Airlock Microgateway Access Control - Metrics",
 "description": "Access control metrics dashboard.",
 "tags": [ "airlock-microgateway" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "operator",
    "label": "Microgateway Operator",
    "query": {
     "query": "label_values(microgateway_build_info,managed_by)"
    }
   },
   {
    "name": "namespace",
    "label": "Gateway Namespace",
    "query": {
     "query": "label_values(microgateway_build_info{managed_by=~\"$operator\"},namespace)"
    }
   },
   {
    "name": "gateway_name",
    "label": "Gateway Name",
    "query": {
     "query": "label_values(microgateway_build_info{managed_by=~\"$operator\", namespace=~\"$namespace\"},gateway)"
    }
   },
   {
    "name": "gateway_httproute",
    "label": "Gateway HTTPRoute",
    "query": {
     "query": "label_values(envoy_cluster_bind_errors{managed_by=~\"$operator\", namespace=~\"$namespace\", gateway=~\"$gateway_name\"},upstream)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Authenticated Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Authenticated Requests",
   "type": "stat",
   "description": "Total number of requests that were successfully authenticated and matched an Access Control policy.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum (increase(microgateway_authenticated_requests_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Non Authorized Request Rate",
   "type": "stat",
   "description": "Rate of authenticated requests that could not be authorized by the matching Access Control policy.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum (increase(microgateway_authenticated_requests_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`, authorized=\"false\"}[$__range])))/\nround(sum (increase(microgateway_authenticated_requests_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
     "legendFormat": "Non Authorized Request Rate"
    }
   ]
  },
  {
   "title": "OIDC: Authenticated Requests",
   "type": "stat",
   "description": "Total number of requests authenticated by OpenID Connect.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum (increase(microgateway_authenticated_requests_total{authentication_method=\"oidc\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "JWT: Authenticated Requests",
   "type": "stat",
   "description": "Total number of requests authenticated by JWT.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum (increase(microgateway_authenticated_requests_total{authentication_method=\"jwt\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Certificate: Authenticated Requests",
   "type": "stat",
   "description": "Total number of requests authenticated by client certificates.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum (increase(microgateway_authenticated_requests_total{authentication_method=\"client_certificate\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Authenticated Requests",
   "type": "timeseries",
   "description": "Rate of requests (per second) that were successfully authenticated and matched an Access Control policy.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (authorized) (rate(microgateway_authenticated_requests_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]))",
     "legendFormat": "Authorized: {{authorized}}"
    }
   ]
  },
  {
   "title": "Top 5 Access Control Policies",
   "type": "barchart",
   "description": "The top 5 Access Control policies by number of matching authenticated requests.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (policy) (increase(microgateway_authenticated_requests_total{result!=\"success\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Authentication Method",
   "type": "timeseries",
   "description": "Rate of requests (per second) by authentication method that were successfully authenticated and matched an Access Control policy.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (authentication_method) (rate(microgateway_authenticated_requests_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non Authorized Request by Authentication Method",
   "type": "timeseries",
   "description": "Rate of requests (per second) by authentication method that were successfully authenticated, matched an Access Control policy, but were not authorized by the matching policy.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (authentication_method) (rate(microgateway_authenticated_requests_total{authorized=\"false\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grant Exchange Requests (Backchannel)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Grant Exchange Requests",
     "type": "stat",
     "description": "Total number of grant exchange backchannel requests to configured OpenID providers.",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum (increase(microgateway_oidc_backchannel_requests_total{request=\"grant_exchange\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "Total Requests"
      }
     ]
    },
    {
     "title": "Grant Exchange Error Rate",
     "type": "stat",
     "description": "Percentage of failed grant exchange backchannel requests to configured OpenID providers.",
     "gridPos": { "h": 5, "w": 5, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum (increase(microgateway_oidc_backchannel_requests_total{request=\"grant_exchange\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`,result!='success'}[$__range])))/\nround(sum (increase(microgateway_oidc_backchannel_requests_total{request=\"grant_exchange\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "Request Error Rate"
      }
     ]
    },
    {
     "title": "Total Grant Exchange Requests",
     "type": "timeseries",
     "description": "Total grant exchange requests per second along with the error rate.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(rate(microgateway_oidc_backchannel_requests_total{request=\"grant_exchange\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]))",
       "legendFormat": "Requests per second"
      },
      {
       "expr": "sum (rate(microgateway_oidc_backchannel_requests_total{request=\"grant_exchange\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`, result!=\"success\"}[1m]))/\nsum (rate(microgateway_oidc_backchannel_requests_total{request=\"grant_exchange\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]))",
       "legendFormat": "Error rate"
      }
     ]
    },
    {
     "title": "Grant Exchange Request Errors",
     "type": "timeseries",
     "description": "Failed grant exchange requests per second by error type.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (result) (rate(microgateway_oidc_backchannel_requests_total{request=\"grant_exchange\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`, result!=\"success\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 5 Access Control Policies by Request Count",
     "type": "barchart",
     "description": "The top 5 Access Control policies with the most grant exchange requests.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum by (policy) (increase(microgateway_oidc_backchannel_requests_total{request=\"grant_exchange\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 5 Access Control Policies by Error Count",
     "type": "barchart",
     "description": "The top 5 Access Control policies with the most faulty grant exchange requests.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum by (policy) (increase(microgateway_oidc_backchannel_requests_total{request=\"grant_exchange\", result!=\"success\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Token Refresh Requests (Backchannel)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Token Refresh Requests",
     "type": "stat",
     "description": "Total number of token refresh backchannel requests to configured OpenID providers.",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum (increase(microgateway_oidc_backchannel_requests_total{request=\"token_refresh\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "Total Requests"
      }
     ]
    },
    {
     "title": "Token Refresh Error Rate",
     "type": "stat",
     "description": "Percentage of failed token refresh backchannel requests to configured OpenID providers.",
     "gridPos": { "h": 5, "w": 5, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum (increase(microgateway_oidc_backchannel_requests_total{request=\"token_refresh\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`,result!='success'}[$__range])))/\nround(sum (increase(microgateway_oidc_backchannel_requests_total{request=\"token_refresh\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "Request Error Rate"
      }
     ]
    },
    {
     "title": "Total Token Refresh Requests",
     "type": "timeseries",
     "description": "Total token refresh requests per second along with the error rate.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum(rate(microgateway_oidc_backchannel_requests_total{request=\"token_refresh\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]))",
       "legendFormat": "Requests per second"
      },
      {
       "expr": "sum (rate(microgateway_oidc_backchannel_requests_total{request=\"token_refresh\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`, result!=\"success\"}[1m]))/\nsum (rate(microgateway_oidc_backchannel_requests_total{request=\"token_refresh\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]))",
       "legendFormat": "Error rate"
      }
     ]
    },
    {
     "title": "Token Refresh Request Errors",
     "type": "timeseries",
     "description": "Failed token refresh requests per second by error type.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (result) (rate(microgateway_oidc_backchannel_requests_total{request=\"token_refresh\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`, result!=\"success\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 5 Access Control Policies by Request Count",
     "type": "barchart",
     "description": "The top 5 Access Control policies with the most token refresh requests.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum by (policy) (increase(microgateway_oidc_backchannel_requests_total{request=\"token_refresh\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 5 Access Control Policies by Error Count",
     "type": "barchart",
     "description": "The top 5 Access Control policies with the most faulty token refresh requests.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum by (policy) (increase(microgateway_oidc_backchannel_requests_total{request=\"token_refresh\", result!=\"success\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Token Introspection Requests (Backchannel)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Token Introspection Requests",
     "type": "stat",
     "description": "Total number of token introspection backchannel requests to configured OpenID providers.",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum (increase(microgateway_oidc_backchannel_requests_total{request=\"introspection\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "Total Requests"
      }
     ]
    },
    {
     "title": "Token Introspection Error Rate",
     "type": "stat",
     "description": "Percentage of failed token introspection backchannel requests to configured OpenID providers",
     "gridPos": { "h": 5, "w": 5, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum (increase(microgateway_oidc_backchannel_requests_total{request=\"introspection\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`,result!='success'}[$__range])))/\nround(sum (increase(microgateway_oidc_backchannel_requests_total{request=\"introspection\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "Request Error Rate"
      }
     ]
    },
    {
     "title": "Total Token Introspection Requests",
     "type": "timeseries",
     "description": "Total token introspection requests per second along with the error rate.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(rate(microgateway_oidc_backchannel_requests_total{request=\"introspection\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]))",
       "legendFormat": "Requests per second"
      },
      {
       "expr": "sum (rate(microgateway_oidc_backchannel_requests_total{request=\"introspection\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`, result!=\"success\"}[1m]))/\nsum (rate(microgateway_oidc_backchannel_requests_total{request=\"introspection\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]))",
       "legendFormat": "Error rate"
      }
     ]
    },
    {
     "title": "Token Introspection Request Errors",
     "type": "timeseries",
     "description": "Failed token introspection requests per second by error type.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (result) (rate(microgateway_oidc_backchannel_requests_total{request=\"introspection\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`, result!=\"success\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 5 Access Control Policies by Request Count",
     "type": "barchart",
     "description": "The top 5 Access Control policies with the most token introspection requests.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum by (policy) (increase(microgateway_oidc_backchannel_requests_total{request=\"introspection\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 5 Access Control Policies by Error Count",
     "type": "barchart",
     "description": "The top 5 Access Control policies with the most faulty token introspection requests.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum by (policy) (increase(microgateway_oidc_backchannel_requests_total{request=\"introspection\", result!=\"success\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Token Exchange Requests (Backchannel)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Token Exchange Requests",
     "type": "stat",
     "description": "Total number of token exchange backchannel requests to configured OpenID providers.",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum (increase(microgateway_token_exchanges_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "Total Requests"
      }
     ]
    },
    {
     "title": "Token Exchange Error Rate",
     "type": "stat",
     "description": "Percentage of failed token exchange backchannel requests to configured OpenID providers.",
     "gridPos": { "h": 5, "w": 5, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum (increase(microgateway_token_exchanges_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`,result!='success'}[$__range])))/\nround(sum (increase(microgateway_token_exchanges_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "Request Error Rate"
      }
     ]
    },
    {
     "title": "Total Token Exchange Requests",
     "type": "timeseries",
     "description": "Total token exchange requests per second along with the error rate.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum(rate(microgateway_token_exchanges_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]))",
       "legendFormat": "Requests per second"
      },
      {
       "expr": "sum (rate(microgateway_token_exchanges_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`, result!=\"success\"}[1m]))/\nsum (rate(microgateway_token_exchanges_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]))",
       "legendFormat": "Error rate"
      }
     ]
    },
    {
     "title": "Token Exchange Request Errors",
     "type": "timeseries",
     "description": "Failed token exchange requests per second by error type.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (result) (rate(microgateway_token_exchanges_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`, result!=\"success\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 5 Access Control Policies by Request Count",
     "type": "barchart",
     "description": "The top 5 Access Control policies with the most token exchange requests.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum by (policy) (increase(microgateway_token_exchanges_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 5 Access Control Policies by Error Count",
     "type": "barchart",
     "description": "The top 5 Access Control policies with the most faulty token exchange requests.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum by (policy) (increase(microgateway_token_exchanges_total{result!=\"success\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}