{{ if .Values.serviceCatalog.enableDevServices }}
---
apiVersion: application.epinio.io/v1
kind: Service
metadata:
  name: mysql-dev
  namespace: {{ .Release.Namespace }}
spec:
  name: mysql-dev
  shortDescription: A MySQL service that can be used during development
  description: |
    This service is going to deploy a simple default Bitnami MySQL db instance.
    You can find more info at https://github.com/bitnami/charts/tree/master/bitnami/mysql/.
    This database is running inside the cluster so it's probably not a good choice for production
    environments, at least with this default configuration.
  chart: mysql
  chartVersion: 9.4.5
  serviceIcon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mysql/img/mysql-stack-110x117.png
  appVersion: 8.0.31
  helmRepo:
    name: bitnami
    url: "https://charts.bitnami.com/bitnami"
  values: |-
    image:
      registry: docker.io
      repository: bitnamilegacy/mysql
    {{- template "epinio.catalog-service-values" . }}
{{- end }}
