{
 "title": "Target Detail",
 "tags": [ "monitoring" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "Cluster", "query": "trilio_system_info" },
   {
    "name": "Scope",
    "query": "trilio_system_info{cluster=~\"$Cluster\"}"
   },
   {
    "name": "Install_Namespace",
    "label": "Install Namespace",
    "query": "trilio_system_info{scope=~\"$Scope\",cluster=~\"$Cluster\"}"
   },
   {
    "name": "Target",
    "label": "Target",
    "query": "trilio_target_info{install_namespace=~\"$Install_Namespace\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>Targets</h1></center>"
   },
   "content": "<center><h1>Targets</h1></center>"
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "avg(trilio_target_info{target=~\"$Target\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Total Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(trilio_backup_storage{target=~\"$Target\",status=~\"Available\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Threshold Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "trilio_target_info{ target=~\"$Target\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Browsing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "trilio_target_info{ target=~\"$Target\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Vendor ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "trilio_target_info{ target=~\"$Target\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Vendor Type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "trilio_target_info{ target=~\"$Target\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Creattion Timestamp",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 2 },
   "format": "dateTimeAsIso",
   "valueName": "first",
   "targets": [
    {
     "expr": "trilio_target_info{ target=~\"$Target\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Backups",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "topk(10,trilio_backup_info{target=~\"$Target\",install_namespace=~\"$Install_Namespace\",cluster=~\"$Cluster\"}) by (size)",
     "legendFormat": "{{backup}} {{status}}"
    }
   ]
  }
 ]
}