{{- if dig "audit" false .Values.enableClusterRoles }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:audit-token-requester
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
# Request a NATS credential for publishing audit events
- apiGroups:
  - identity.k8s.appscode.com
  resources:
  - audittokenrequests
  verbs: ["create"]

{{- end }}
