{{- if .Values.apiService.create }}
{{- range $version := list "v1beta1" "v1beta2" }}
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: {{ $version }}.custom.metrics.k8s.io
  labels:
    {{- include "storage-metrics-server.labels" $ | nindent 4 }}
spec:
  group: custom.metrics.k8s.io
  version: {{ $version }}
  service:
    name: {{ include "storage-metrics-server.fullname" $ }}
    namespace: {{ $.Release.Namespace }}
    port: {{ $.Values.service.port }}
  insecureSkipTLSVerify: {{ $.Values.apiService.insecureSkipTLSVerify }}
  groupPriorityMinimum: {{ $.Values.apiService.groupPriorityMinimum }}
  versionPriority: {{ $.Values.apiService.versionPriority }}
{{- end }}
{{- end }}
