apiVersion: v1
kind: Service
metadata:
  name: {{ include "storage-metrics-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "storage-metrics-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: https
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "storage-metrics-server.selectorLabels" . | nindent 4 }}
