apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "storage-metrics-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "storage-metrics-server.labels" . | nindent 4 }}
