apiVersion: v2
appVersion: 2.1.0
description: Gateway API definitions chart
home: https://docs.gluu.org
icon: https://gluu.org/docs/gluu-server/favicon.ico
keywords:
- application load balancer
- Gateway API
kubeVersion: '>=v1.23.0-0'
maintainers:
- email: team@gluu.org
  name: Mohammad Abudayyeh
  url: https://github.com/moabu
name: gateway-api
sources:
- https://github.com/GluuFederation/flex/tree/main/charts/gluu/charts/gateway-api
type: application
version: 2.1.0
