annotations:
  artifacthub.io/changes: "- \"fix(hub): :bug: guard nil hub.token in hub-license
    template\"\n- \"feat(proxy): :rocket: support traefik v3.7.4\"\n- \"feat(provider):
    :sparkles: support qps and burst on kubernetesGateway\"\n- \"feat(logs): :sparkles:
    support accesslog query parameters defaultmode\"\n- \"feat(hub): :rocket: support
    traefik hub v3.20.4\"\n- \"feat(CRDs): update Traefik Hub CRDs to v1.31.0\"\n-
    \"chore(release): \U0001F680 publish 40.3.0\"\n- \"chore(deps): support traefik
    v3.7.3 & hub v3.20.3\"\n- \"chore(ci): track proxy & hub max-version annotations
    with renovate\"\n"
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Traefik Proxy
  catalog.cattle.io/kube-version: '>=1.25.0-0'
  catalog.cattle.io/release-name: traefik
  traefik.io/hub-max-version: v3.20.4
  traefik.io/hub-min-version: v3.19.3
  traefik.io/proxy-max-version: v3.7.4
  traefik.io/proxy-min-version: v3.6.0
apiVersion: v2
appVersion: v3.7.4
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: file://assets/icons/traefik.png
keywords:
- traefik
- ingress
- networking
kubeVersion: '>=1.25.0-0'
maintainers:
- email: michel.loiseleur@traefik.io
  name: mloiseleur
- email: remi.buisson@traefik.io
  name: darkweaver87
- name: jnoordsij
name: traefik
sources:
- https://github.com/traefik/traefik-helm-chart
- https://github.com/traefik/traefik
type: application
version: 40.3.0
