annotations:
  artifacthub.io/changes: "- \"fix: support enabling only kubernetesIngressNGINX with
    rbac.namespaced\"\n- \"fix(rbac): :bug: align namespaced RBAC with kubernetesIngressNGINX
    namespace scoping\"\n- \"fix(ports): support IPv6 hostIP values\"\n- \"fix(deployment):
    :bug: accept named port for healthchecksPort\"\n- \"feat(rbac): grant configmaps
    write for hub api management\"\n- \"feat(hub): add hardened image variant\"\n-
    \"feat(hub): :sparkles: add hub.enabled to run Traefik Hub in proxy mode\"\n-
    \"feat(deps): update traefik docker tag to v3.7.9\"\n- \"feat(deps): update traefik
    docker tag to v3.7.8\"\n- \"feat(deps): update traefik docker tag to v3.7.7\"\n-
    \"feat(deps): update ghcr.io/traefik/traefik-hub docker tag to v3.20.7\"\n- \"feat(CRDs):
    update Traefik Hub to v1.33.0\"\n- \"docs: :books: change metrics.prometheus labels
    types from string to bool\"\n- \"docs(values): :books: fix rendered types for
    nullable fields\"\n- \"chore: :art: file provider scrambled output\"\n- \"chore(release):
    \U0001F680 publish 41.1.0 and hub-manager 1.0.0\"\n"
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Traefik Proxy
  catalog.cattle.io/kube-version: '>=1.25.0-0'
  catalog.cattle.io/release-name: traefik
  traefik.io/hub-max-version: v3.20.7
  traefik.io/hub-min-version: v3.19.3
  traefik.io/proxy-max-version: v3.7.9
  traefik.io/proxy-min-version: v3.6.0
apiVersion: v2
appVersion: v3.7.9
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: file://assets/icons/traefik.png
keywords:
- traefik
- ingress
- networking
kubeVersion: '>=1.25.0-0'
maintainers:
- email: michel.loiseleur@traefik.io
  name: mloiseleur
- email: remi.buisson@traefik.io
  name: darkweaver87
- name: jnoordsij
name: traefik
sources:
- https://github.com/traefik/traefik-helm-chart
- https://github.com/traefik/traefik
type: application
version: 41.1.0
