
{{- $protocol := "http" -}}
{{- if .Values.web.ingress.tls -}}
{{- $protocol = "https" -}}
{{- end -}}
{{- $host := .Values.web.ingress.host -}}

{{- $apiProtocol := "http" -}}
{{- if .Values.api.ingress.tls -}}
{{- $apiProtocol = "https" -}}
{{- end -}}
{{- $apiHost := .Values.api.ingress.host -}}
{{- $apiImage := include "devguard.image" (dict "image" .Values.api.image "defaultTag" .Chart.AppVersion) -}}
{{- $apiImagePullPolicy := include "devguard.imagePullPolicy" (dict "image" .Values.api.image) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devguard-api-deployment
  labels:
    {{- include "devguard.labels" . | nindent 4 }}
    app: devguard-api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      app: devguard-api
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "devguard.labels" . | nindent 8 }}
        {{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: devguard-api
        version: {{ .Chart.AppVersion }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 53111
        runAsGroup: 3000
        fsGroup: 2000
      initContainers:
        - name: "devguard-migrate"
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 53111
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
          image: {{ $apiImage | quote }}
          imagePullPolicy: {{ $apiImagePullPolicy }}
          resources:
            {{- toYaml .Values.api.migrate.resources | nindent 12 }}
          env:
          - name: POSTGRES_DB
            value: devguard
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgres-password
                name: db-secret
          - name: FRONTEND_URL
            value: {{ printf "%s://%s" $protocol $host }}
          - name: POSTGRES_USER
            value: devguard
          - name: POSTGRES_HOST
            value: postgresql
          - name: POSTGRES_PORT
            value: "5432"
          - name: GOMEMLIMIT
            value: 1024MiB
          command: ["devguard-cli", "migrate"]
          volumeMounts:
          - mountPath: /tmp
            name: tmp-dir
        - name: "devguard-encryption-migration"
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 53111
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
          image: {{ $apiImage | quote }}
          imagePullPolicy: {{ $apiImagePullPolicy }}
          resources:
            {{- toYaml .Values.api.migrate.resources | nindent 12 }}
          env:
          - name: POSTGRES_DB
            value: devguard
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgres-password
                name: db-secret
          - name: POSTGRES_USER
            value: devguard
          - name: POSTGRES_HOST
            value: postgresql
          - name: POSTGRES_PORT
            value: "5432"
          - name: APP_SIDE_ENCRYPTION_KEY_PATH
            value: /encryption/key
          command: ["devguard-cli", "encryption", "migration"]
          volumeMounts:
          - mountPath: /tmp
            name: tmp-dir
          - mountPath: /encryption
            name: encryption-key
            readOnly: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 53111
            runAsNonRoot: true
            capabilities:
                drop:
                - ALL
          image: {{ $apiImage | quote }}
          imagePullPolicy: {{ $apiImagePullPolicy }}
          env:
          - name: POSTGRES_DB
            value: devguard
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgres-password
                name: db-secret
          - name: POSTGRES_USER
            value: devguard
          - name: POSTGRES_HOST
            value: postgresql
          - name: OSI_LICENSES_API
            value: https://opensource.org/api/license/
          - name: POSTGRES_PORT
            value: "5432"
          - name: DEVGUARD_CI_COMPONENT_BASE
            value: {{ .Values.api.ciComponentBase | quote }}
          - name: FRONTEND_URL
            value: {{ printf "%s://%s" $protocol $host }}
          - name: PROFILE
            value: {{ .Values.api.debug.profile | quote }}
          - name: PPROF_PASSWORD
            valueFrom:
              secretKeyRef:
                name: devguard-pprof-password
                key: password
          - name: INSTANCE_DOMAIN
            {{- if .Values.api.ingress.enabled }}
            value: {{ printf "%s://%s" $apiProtocol $apiHost }}
            {{- else }}
            value: http://devguard-api-service.{{ .Release.Namespace }}.svc.cluster.local:8080
            {{- end }}
        {{- if .Values.api.adminPublicKey }}
          - name: INSTANCE_ADMIN_PUB_KEY_PATH
            value: /instance_admin_pub_key.pem
        {{- end }}
          - name: ORY_KRATOS_PUBLIC
            value: http://kratos:4433
          - name: ORY_KRATOS_ADMIN
            value: http://kratos:4434
          - name: GOMEMLIMIT
            value: 1024MiB
          - name: PDF_GENERATION_API
            value: https://dwt-api.dev-l3montree.cloud/pdf
          - name: DEPENDENCY_PROXY_CACHE_DIR
            value: /tmp/dependency-proxy-cache
        {{- if .Values.api.csaf.existingCsafSecretName }}
          - name: CSAF_OPENPGP_PASSPHRASE
            valueFrom:
              secretKeyRef:
                key: passphrase
                name: {{ .Values.api.csaf.existingCsafSecretName }}
                optional: true
          - name: CSAF_OPENPGP_FINGERPRINT
            valueFrom:
              secretKeyRef:
                key: fingerprint
                name: {{ .Values.api.csaf.existingCsafSecretName }}
                optional: true
          - name: CSAF_OPENPGP_PRIVATE_KEY_PATH
            value: /csaf-private-key.asc
          - name: CSAF_OPENPGP_PUBLIC_KEY_PATH
            value: /csaf-public-key.asc
        {{- end }}
          - name: CSAF_AGGREGATOR_NAME
            value: {{ .Values.api.csaf.aggregatorName | quote }}
          - name: CSAF_AGGREGATOR_NAMESPACE
            value: {{ .Values.api.csaf.aggregatorNamespace | quote }}
          - name: CSAF_AGGREGATOR_CONTACT_DETAILS
            value: {{ .Values.api.csaf.aggregatorContactDetails | quote }}

        {{- range .Values.kratos.oidc.providers }}
            {{- if eq .provider "gitlab" }}
          - name: GITLAB_{{ .id | upper }}_APPID
            value: {{ .clientId | quote }}
          - name: GITLAB_{{ .id | upper }}_APPSECRET
            valueFrom:
              secretKeyRef:
                key: secret
                name: {{ .existingClientSecretName | quote }}
          - name: GITLAB_{{ .id | upper }}_BASEURL
            value: {{ .issuerUrl | quote }}
          - name: GITLAB_{{ .id | upper }}_DISABLETICKETSYNC
            value: "{{ .disableTicketSync | default false }}"
          - name: GITLAB_{{ .id | upper }}_SCOPES
            value: {{ .scope | join " " | quote }}
            {{- if .existingBotUserSecretName }}
          - name: GITLAB_{{ .id | upper }}_BOTUSERID
            value: {{ .botUserId | quote }}
          - name: GITLAB_{{ .id | upper }}_BOTUSERACCESSTOKEN
            valueFrom:
              secretKeyRef:
                key: accessToken
                name: {{ .existingBotUserSecretName | quote }}
            {{- end }}
            {{- if .existingAdminTokenSecretName }}
          - name: GITLAB_{{ .id | upper }}_ADMINTOKEN
            valueFrom:
              secretKeyRef:
                key: token
                name: {{ .existingAdminTokenSecretName | quote }}
            {{- end }}
            {{- if .autosetupApplication}}
          - name: GITLAB_{{ .id | upper }}AUTOSETUP_APPID
            value: {{ .autosetupApplication.clientId | quote }}
          - name: GITLAB_{{ .id | upper }}AUTOSETUP_APPSECRET
            valueFrom:
              secretKeyRef:
                key: secret
                name: {{ .autosetupApplication.existingClientSecretName | quote }}
          - name: GITLAB_{{ .id | upper }}AUTOSETUP_BASEURL
            value: {{ .issuerUrl | quote }}
          - name: GITLAB_{{ .id | upper }}AUTOSETUP_SCOPES
            value: {{ .autosetupApplication.scope | join " " | quote }}
            {{- end }}
            {{- end }}
        {{- end }}
          - name: API_URL
            value: {{ .Values.web.devguardApiUrlPublicInternet }}
        {{- if .Values.api.github.enabled }}
          - name: GITHUB_APP_ID
            value: {{ .Values.api.github.appId | quote }}
          - name: GITHUB_PRIVATE_KEY
            value: /github-app-private-key
          - name: GITHUB_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                key: webhookSecret
                name: {{ .Values.api.github.existingWebhookSecretSecretName }}
                optional: true
        {{- end }}
        {{- if and .Values.api.errorTracking.dsn .Values.api.errorTracking.environment }}
          - name: ERROR_TRACKING_DSN
            value: {{ .Values.api.errorTracking.dsn | quote }}
          - name: ENVIRONMENT
            value: {{ .Values.api.errorTracking.environment | quote }}
        {{- end }}
          - name: APP_SIDE_ENCRYPTION_KEY_PATH
            value: /encryption/key
          - name: TRACES_SAMPLE_RATE
            value: {{ .Values.api.tracing.sampleRate | quote }}
        {{- if .Values.api.tracing.enabled }}
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "grpc://localhost:4317"
        {{- end }}
        {{- range $key, $val := .Values.api.additionalEnvs }}
          - name: {{ $key }}
            value: {{ tpl $val $ | quote }}
        {{- end }}
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /github-app-private-key
            name: github-app-private-key
            subPath: privateKey
          - mountPath: /intoto-private-key.pem
            name: intoto-private-key
            subPath: privateKey
          {{- if .Values.api.csaf.existingCsafSecretName }}
          - mountPath: /csaf-private-key.asc
            name: csaf-keys
            subPath: privateKey
          - mountPath: /csaf-public-key.asc
            name: csaf-keys
            subPath: publicKey
          {{- end }}
          - mountPath: /tmp
            name: tmp-dir
          - mountPath: /encryption
            name: encryption-key
            readOnly: true
          {{- if .Values.api.adminPublicKey }}
          - mountPath: /instance_admin_pub_key.pem
            name: instance-admin-pub-key
            subPath: publicKey
            readOnly: true
          {{- end }}
        {{- if .Values.api.tracing.enabled }}
        - name: otel-collector
          image: "{{ .Values.api.tracing.spanMetrics.image.repository }}:{{ .Values.api.tracing.spanMetrics.image.tag }}"
          args:
            - "--config=/etc/otel/config.yaml"
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
            - name: span-metrics
              containerPort: 8889
          {{- if .Values.api.tracing.existingSecretName }}
          env:
            - name: OTEL_EXPORTER_BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api.tracing.existingSecretName }}
                  key: username
            - name: OTEL_EXPORTER_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api.tracing.existingSecretName }}
                  key: password
          {{- end }}
          volumeMounts:
            - name: otel-collector-config
              mountPath: /etc/otel/config.yaml
              subPath: config.yaml
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.api.tracing.spanMetrics.resources | nindent 12 }}
        {{- end }}
      volumes:
      - name: github-app-private-key
        secret:
          secretName: {{ .Values.api.github.existingPrivateKeySecretName }}
          optional: true
      - name: intoto-private-key
        secret:
          secretName: {{ .Values.api.intoto.existingPrivateKeySecretName }}
      {{- if .Values.api.csaf.existingCsafSecretName }}
      - name: csaf-keys
        secret:
          secretName: {{ .Values.api.csaf.existingCsafSecretName }}
      {{- end }}
      - name: encryption-key
        secret:
          secretName: devguard-encryption-key
      {{- if .Values.api.adminPublicKey }}
      - name: instance-admin-pub-key
        secret:
          secretName: devguard-instance-admin-pub-key
      {{- end }}
      # Vulndb updates are downloaded to tmp
      - name: tmp-dir
        emptyDir:
          sizeLimit: 8Gi
      {{- if .Values.api.tracing.enabled }}
      - name: otel-collector-config
        configMap:
          name: otel-collector-sidecar-config
      {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
