{{- if not .Values.api.useExistingEncryptionKeySecret }}
{{- $secretName := "devguard-encryption-key" -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "devguard.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $existing }}
  key: {{ index $existing.data "key" | b64dec }}
  {{- else }}
  key: {{ randAlphaNum 32 | sha256sum }}
  {{- end }}
{{- end }}
