{{- if .Values.api.adminPublicKey }}
apiVersion: v1
kind: Secret
metadata:
  name: devguard-instance-admin-pub-key
  labels:
    {{- include "devguard.labels" . | nindent 4 }}
type: Opaque
stringData:
  publicKey: {{ .Values.api.adminPublicKey | quote }}
{{- end }}
