operatorImage: europe-docker.pkg.dev/kubemq/images/kubemq-operator:next
kubemqImage: europe-docker.pkg.dev/kubemq/images/kubemq:next
connectorTargetsImage: kubemq/kubemq-targets:latest
connectorSourcesImage: kubemq/kubemq-sources:latest
connectorBridgesImage: kubemq/kubemq-bridges:latest

# Image pull secrets for private registries
# Reference existing secrets created by kubectl or other methods
# Example:
#   imagePullSecrets:
#     - name: my-registry-secret
imagePullSecrets: []