#!/usr/bin/env bash
set -e
set -x

for f in packages/*; do
  if [[ -f ${f}/package.yaml ]]; then
  	if [[ -z $CHART || $CHART == $(basename -- ${f}) ]]; then
			mkdir -p ${f}/charts-original
			url=$(cat ${f}/package.yaml | yq r - url)
			subdirectory=$(cat ${f}/package.yaml | yq r - subdirectory)
			type=$(cat ${f}/package.yaml | yq r - type)
			commit=$(cat ${f}/package.yaml | yq r - commit)
			fields=$(echo ${subdirectory} | awk -F'/' '{print NF}')
			if [[ $fields -eq '0' ]]; then
				fields='1'
			fi
			if [[ $type == 'git' ]]; then
				mkdir -p /tmp/tmp-charts
				git clone $url /tmp/tmp-charts
				pwd=$(pwd)
				cd /tmp/tmp-charts/${subdirectory}
				git checkout $commit
				cd $pwd
				cp -r /tmp/tmp-charts/${subdirectory}/* ${f}/charts-original
				rm -rf /tmp/tmp-charts
			else
				curl -sLf ${url} | tar xvzf - -C ${f}/charts-original --strip ${fields} ${subdirectory} > /dev/null 2>&1
			fi
			if [[ -d ${f}/charts ]]; then
				diff -uNr ${f}/charts-original ${f}/charts > ${f}/$(basename -- ${f}).patch || true
			fi
			rm -rf ${f}/charts-original
		fi
  fi
done