{{/* Autogenerated, do NOT modify */}}
{{- define "k10.grafanaImageTag" -}}9.1.5{{- end -}}
{{- define "k10.grafanaInitContainerImageRepo" -}}registry.access.redhat.com/ubi9/ubi-minimal{{- end -}}
{{- define "k10.grafanaInitContainerImageTag" -}}9.1.0-1656.1669627757{{- end -}}
