apiVersion: v1
data:
  ca-key.pem: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0
    NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ28yblFyQ1d4NHNuVVNaNmsKdm91YmFpRkJSZytV
    YTZNOHhWMUdyWkFoNGphaFJBTkNBQVJIVUhZV0ZXa0dmOFdKVlFxdmo2WUF4L3dWRnhhVA
    p3a1B4VzFVSytNK3FvNmwzMW5GeWlUVlI2M2RoVENDYjYyV1lmQytkM3dKYnhicGJ5dHFo
    dDJ1YgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t
  ca.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsVENDQVR1Z0F3SUJBZ0lJQ3lZU3
    UyVzM1eTh3Q2dZSUtvWkl6ajBFQXdRd1BqRVRNQkVHQTFVRUJ4TUsKUzNWaVpYSnVaWFJs
    Y3pFTU1Bb0dBMVVFQmhNRFJFVldNUmt3RndZRFZRUURFeEJQY0dWeVlYUnZjaUJTYjI5MA
    pJRU5CTUI0WERUSTFNVEV4T0RBd01EQXdNRm9YRFRNd01URXhPREF3TURBd01Gb3dQakVU
    TUJFR0ExVUVCeE1LClMzVmlaWEp1WlhSbGN6RU1NQW9HQTFVRUJoTURSRVZXTVJrd0Z3WU
    RWUVFERXhCUGNHVnlZWFJ2Y2lCU2IyOTAKSUVOQk1Ga3dFd1lIS29aSXpqMENBUVlJS29a
    SXpqMERBUWNEUWdBRVIxQjJGaFZwQm4vRmlWVUtyNCttQU1mOApGUmNXazhKRDhWdFZDdm
    pQcXFPcGQ5Wnhjb2sxVWV0M1lVd2dtK3RsbUh3dm5kOENXOFc2VzhyYW9iZHJtNk1qCk1D
    RXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WSFE4QkFmOEVCQU1DQVNZd0NnWUlLb1
    pJemowRUF3UUQKU0FBd1JRSWhBS2Rtb0VuZG1FcGZqZmlSa01Oc05xVWdjQTFNNXVrblNP
    WXNjUnErVldKeEFpQk9ZS25INytlSgpVeS9VOUVWS3JzVURqOGgrZFZJUjBZeGFIekFpVG
    VZM09nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
kind: Secret
metadata:
  labels:
    operator: dxoperator-v2
  name: dxoperator-v2-webhook-ca-64hmmfgtc7
  namespace: dxoperator-v2-system
type: Opaque
