apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    operator: dxoperator-v2
  name: dxoperator-v2-mutators
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsVENDQVR1Z0F3SUJBZ0lJQ3lZU3UyVzM1eTh3Q2dZSUtvWkl6ajBFQXdRd1BqRVRNQkVHQTFVRUJ4TUsKUzNWaVpYSnVaWFJsY3pFTU1Bb0dBMVVFQmhNRFJFVldNUmt3RndZRFZRUURFeEJQY0dWeVlYUnZjaUJTYjI5MApJRU5CTUI0WERUSTFNVEV4T0RBd01EQXdNRm9YRFRNd01URXhPREF3TURBd01Gb3dQakVUTUJFR0ExVUVCeE1LClMzVmlaWEp1WlhSbGN6RU1NQW9HQTFVRUJoTURSRVZXTVJrd0Z3WURWUVFERXhCUGNHVnlZWFJ2Y2lCU2IyOTAKSUVOQk1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRVIxQjJGaFZwQm4vRmlWVUtyNCttQU1mOApGUmNXazhKRDhWdFZDdmpQcXFPcGQ5Wnhjb2sxVWV0M1lVd2dtK3RsbUh3dm5kOENXOFc2VzhyYW9iZHJtNk1qCk1DRXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WSFE4QkFmOEVCQU1DQVNZd0NnWUlLb1pJemowRUF3UUQKU0FBd1JRSWhBS2Rtb0VuZG1FcGZqZmlSa01Oc05xVWdjQTFNNXVrblNPWXNjUnErVldKeEFpQk9ZS25INytlSgpVeS9VOUVWS3JzVURqOGgrZFZJUjBZeGFIekFpVGVZM09nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    service:
      name: dxoperator-v2-operator
      namespace: dxoperator-v2-system
      path: /mutate/sqlagentity
  matchPolicy: Exact
  name: mutate.dxsqlag.dh2i.com.v1
  rules:
  - apiGroups:
    - dh2i.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dxsqlags
  sideEffects: None
