apiVersion: v1
kind: Service
metadata:
  labels:
    operator: dxoperator-v2
    operator-deployment: kubernetes-operator
    operator-element: operator-svc
  name: dxoperator-v2-operator
  namespace: dxoperator-v2-system
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    operator: dxoperator-v2
    operator-deployment: kubernetes-operator
    {{- include "dxoperator.selectorLabels" . | nindent 4 }}
