annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: HariKube
  catalog.cattle.io/kube-version: '>=1.34.0-0'
  catalog.cattle.io/release-name: harikube
apiVersion: v2
name: harikube
description: A Helm chart for HariKube
icon: file://assets/icons/harikube.png
type: application
version: 0.15.0
appVersion: 0.15.0
kubeVersion: ">=1.34.0-0"
dependencies:
- name: vcluster
  version: "0.32.1"
  repository: "https://charts.loft.sh"