{{- if ((.Values.namespaced | default dict).enabled | default false) }}
{{- if .Values.namespaced.forwarder.enabled }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
{{- with .Values.namespaced.image.pullSecrets }}
imagePullSecrets: {{ toYaml . | nindent 2 }}
{{- end }}
metadata:
  name: speedscale-forwarder
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- with .Values.namespaced.globalLabels }}
{{ toYaml . | indent 4 }}
    {{- end }}
    app: speedscale-forwarder
    controlplane.speedscale.com/component: forwarder
  {{- $annotations := deepCopy (.Values.namespaced.globalAnnotations | default dict) }}
  {{- if eq .Values.namespaced.forwarder.primaryTransport "byoc" }}
  {{- $annotations = mergeOverwrite $annotations (.Values.namespaced.forwarder.byoc.serviceAccountAnnotations | default dict) }}
  {{- end }}
  {{- with $annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- end }}
