{{- if ((.Values.namespaced | default dict).enabled | default false) }}
{{- if .Values.namespaced.pdb.enabled }}
{{- if .Values.namespaced.forwarder.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: speedscale-forwarder
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- with .Values.namespaced.globalLabels }}
{{ toYaml . | indent 4 }}
    {{- end }}
    app: speedscale-forwarder
    controlplane.speedscale.com/component: forwarder
  {{- with .Values.namespaced.globalAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  minAvailable: {{ .Values.namespaced.pdb.minAvailable }}
  selector:
    matchLabels:
      app: speedscale-forwarder
      controlplane.speedscale.com/component: forwarder
{{- end }}
{{- if .Values.namespaced.inspector.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: speedscale-inspector
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- with .Values.namespaced.globalLabels }}
{{ toYaml . | indent 4 }}
    {{- end }}
    app: speedscale-inspector
    controlplane.speedscale.com/component: inspector
  {{- with .Values.namespaced.globalAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  minAvailable: {{ .Values.namespaced.pdb.minAvailable }}
  selector:
    matchLabels:
      app: speedscale-inspector
      controlplane.speedscale.com/component: inspector
{{- end }}
{{- end }}

{{- end }}
