{{- if ((.Values.namespaced | default dict).enabled | default false) }}
{{- if .Values.namespaced.inspector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: speedscale-inspector
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- with .Values.namespaced.globalLabels }}
{{ toYaml . | indent 4 }}
    {{- end }}
    app: speedscale-inspector
    controlplane.speedscale.com/component: inspector
  {{- with .Values.namespaced.globalAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: speedscale-inspector
    controlplane.speedscale.com/component: inspector
{{- end }}

{{- end }}
