{{- if ((.Values.namespaced | default dict).enabled | default false) }}
{{- if .Values.namespaced.inspector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedscale-inspector
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- with .Values.namespaced.globalLabels }}
{{ toYaml . | indent 4 }}
    {{- end }}
    app: speedscale-inspector
    controlplane.speedscale.com/component: inspector
  annotations:
    {{- with .Values.namespaced.globalAnnotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
    operator.speedscale.com/ignore: "true"
    speedscale.com/install-mode: namespaced
spec:
  replicas: {{ .Values.namespaced.inspector.replicas | default 1 }}
  selector:
    matchLabels:
      app: speedscale-inspector
      controlplane.speedscale.com/component: inspector
  template:
    metadata:
      annotations:
        {{- with .Values.namespaced.globalAnnotations }}
{{ toYaml . | indent 8 }}
        {{- end }}
        checksum/config: '{{ include (print $.Template.BasePath "/namespaced-inspector-configmap.yaml") . | sha256sum }}'
      labels:
        {{- with .Values.namespaced.globalLabels }}
{{ toYaml . | indent 8 }}
        {{- end }}
        app: speedscale-inspector
        controlplane.speedscale.com/component: inspector
    spec:
      serviceAccountName: '{{ include "speedscale.namespaced.inspectorServiceAccountName" . }}'
      securityContext: {{- toYaml .Values.namespaced.globalSecurityContext | nindent 8 }}
      containers:
      - name: speedscale-inspector
        image: '{{ .Values.namespaced.image.registry }}/inspector:{{ .Values.namespaced.image.tag }}'
        imagePullPolicy: '{{ .Values.namespaced.image.pullPolicy }}'
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SPEEDSCALE_APP_URL
          value: '{{ .Values.namespaced.appUrl }}'
        envFrom:
        - configMapRef:
            name: speedscale-inspector
        - secretRef:
            name: '{{ include "speedscale.namespaced.apiKeySecretName" . }}'
            optional: false
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 30
          grpc:
            port: 6666
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 30
          grpc:
            port: 6666
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 3
        resources: {{- toYaml .Values.namespaced.inspector.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.namespaced.globalPodSecurityContext | nindent 10 }}
        volumeMounts:
        - mountPath: /tmp
          name: speedscale-diagnostics
        {{- if .Values.namespaced.kerberos.enabled }}
        - mountPath: /etc/speedscale/kerberos
          name: speedscale-kerberos
          readOnly: true
        {{- end }}
      volumes:
      - emptyDir: {}
        name: speedscale-diagnostics
      {{- if .Values.namespaced.kerberos.enabled }}
      - name: speedscale-kerberos
        secret:
          secretName: {{ .Values.namespaced.kerberos.secretName | quote }}
          items:
          - key: krb5.conf
            path: krb5.conf
          {{- if eq .Values.namespaced.kerberos.credentialSource "keytab" }}
          - key: client.keytab
            path: client.keytab
          {{- else }}
          - key: cache
            path: cache
          {{- end }}
      {{- end }}
      {{- with .Values.namespaced.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.namespaced.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.namespaced.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

{{- end }}
