apiVersion: v1
kind: Service
metadata:
  name: airlock-microgateway-operator-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airlock-microgateway.labels" . | nindent 4 }}
    {{- with .Values.serviceLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with mustMerge .Values.serviceAnnotations .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - appProtocol: http
    name: metrics
    port: 8080
    protocol: TCP
  selector:
    {{- include "airlock-microgateway.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: airlock-microgateway-operator-leader-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airlock-microgateway.labels" . | nindent 4 }}
    {{- with .Values.serviceLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    operator.microgateway.airlock.com/isLeader: "true"
  {{- with mustMerge .Values.serviceAnnotations .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - appProtocol: http
      name: metrics
      port: 8080
      protocol: TCP
  selector:
    {{- include "airlock-microgateway.selectorLabels" . | nindent 4 }}
    operator.microgateway.airlock.com/isLeader: "true"