{{- if .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alchemi-ai.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "alchemi-ai.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config.data | nindent 2 }}
{{- end }}
