apiVersion: v2
appVersion: 1.0.5
description: Alchemi Zenith superadmin portal (Next.js)
home: https://alchemistudio.ai
keywords:
- alchemi
- zenith
- admin
maintainers:
- name: Alchemi Platform Team
name: alchemi-zenith
type: application
version: 1.0.5
