annotations:
  artifacthub.io/changes: "- \"fix(crds): add missing hub.traefik.io_uplinks to kustomization\"\n-
    \"feat(deps): update traefik docker tag to v3.7.6\"\n- \"feat(deps): update ghcr.io/traefik/traefik-hub
    docker tag to v3.20.6\"\n- \"chore(release): \U0001F680 publish 41.0.2\"\n"
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Traefik Proxy
  catalog.cattle.io/kube-version: '>=1.25.0-0'
  catalog.cattle.io/release-name: traefik
  traefik.io/hub-max-version: v3.20.6
  traefik.io/hub-min-version: v3.19.3
  traefik.io/proxy-max-version: v3.7.6
  traefik.io/proxy-min-version: v3.6.0
apiVersion: v2
appVersion: v3.7.6
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: file://assets/icons/traefik.png
keywords:
- traefik
- ingress
- networking
kubeVersion: '>=1.25.0-0'
maintainers:
- email: michel.loiseleur@traefik.io
  name: mloiseleur
- email: remi.buisson@traefik.io
  name: darkweaver87
- name: jnoordsij
name: traefik
sources:
- https://github.com/traefik/traefik-helm-chart
- https://github.com/traefik/traefik
type: application
version: 41.0.2
