{{- if not .Values.api.useExistingPprofPasswordSecret }}
{{- $secretName := "devguard-pprof-password" -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "devguard.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ if $existing }}{{ index $existing.data "password" | b64dec }}{{ else }}{{ randAlphaNum 32 }}{{ end }}
{{- end }}
