annotations:
  charts.openshift.io/name: sidekick
apiVersion: v2
appVersion: v0.0.14
description: A Helm chart for Sidekick Operator by AppsCode
home: https://github.com/kubeops/sidekick
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
kubeVersion: '>=1.28.0-0'
maintainers:
- email: support@appscode.com
  name: appscode
name: sidekick
sources:
- https://github.com/kubeops/sidekick
type: application
version: v2026.2.16
