annotations:
  artifacthub.io/category: security
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Airlock Microgateway Documentation
      url: https://docs.airlock.com/microgateway/5.1/
    - name: Airlock Microgateway Labs
      url: https://airlock.instruqt.com/pages/airlock-microgateway-labs
    - name: Airlock Microgateway Forum
      url: https://forum.airlock.com/
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Seamless Upgrades
  artifacthub.io/prerelease: "false"
  artifacthub.io/signKey: |
    fingerprint: CFB1AEC6275529B7DD681691594C8F4B7423CA8FEDA8AFE8634682D00F853242
    url: https://raw.githubusercontent.com/airlock/microgateway/main/cosign/cosign.pub
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Airlock Microgateway
  catalog.cattle.io/kube-version: '>=1.30.0-0'
  catalog.cattle.io/release-name: microgateway
  charts.openshift.io/name: Airlock Microgateway
apiVersion: v2
appVersion: 5.1.1
description: A Helm chart for deploying the Airlock Microgateway
home: https://www.airlock.com/en/microgateway
icon: file://assets/icons/microgateway.svg
keywords:
- Gateway API
- WAF
- Web Application Firewall
- WAAP
- Web Application and API protection
- OWASP
- Airlock
- Microgateway
- Security
- Filtering
- DevSecOps
- shift left
- control plane
- Operator
- Token exchange
- OIDC
- JWT
kubeVersion: '>=1.30.0-0'
maintainers:
- email: support@airlock.com
  name: Airlock
  url: https://www.airlock.com/
name: microgateway
sources:
- https://github.com/airlock/microgateway
type: application
version: 5.1.1
