apiVersion: v1
kind: Service
metadata:
  name: devguard-api-service
  labels:
    app: devguard-api
    {{- include "devguard.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.api.tracing.enabled }}
    - port: 8889
      targetPort: span-metrics
      protocol: TCP
      name: span-metrics
    {{- end }}
  selector:
    app: devguard-api
