---
{{- if .Values.quobyte.s3.enabled }}
# This is a loadbalancer service in order to get svc entries in kube-dns
apiVersion: v1
kind: Service
metadata:
  name: quobyte-s3
  {{- if .Values.quobyte.lbinternal }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  {{- end }}
  labels:
    app: quobyte-s3
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: "quobyte-s3"
      protocol: "TCP"
      targetPort: 80
  selector:
    app: quobyte-s3

{{- end }}
