{{- if and .Values.observability.serviceMonitor.enabled .Values.api.tracing.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devguard-api
  labels:
    {{- include "devguard.labels" . | nindent 4 }}
    {{- with .Values.observability.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: devguard-api
  endpoints:
  {{- if .Values.api.tracing.enabled }}
  - port: span-metrics
    path: /metrics
    interval: {{ .Values.observability.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.observability.serviceMonitor.scrapeTimeout }}
  {{- end }}
{{- end }}
