annotations:
  charts.openshift.io/name: kubedb-metrics
apiVersion: v2
appVersion: v2026.2.26
description: KubeDB State Metrics
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
kubeVersion: '>=1.28.0-0'
maintainers:
- email: support@appscode.com
  name: appscode
name: kubedb-metrics
sources:
- https://github.com/kubedb
type: application
version: v2026.2.26
