{{- if .Values.features.csiDriverIntegration }}
{{- if (gt (int .Values.backupCsiDriver.controller.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "backup-csi-driver.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backup-csi-driver.controllerSelectorLabels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "backup-csi-driver.controllerSelectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
