{{- if .Values.features.csiDriverIntegration }}
{{- $sa := .Values.backupCsiDriver.kopiaServer.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backup-csi-driver.fullname" . }}-controller-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backup-csi-driver.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- if and $sa.azureClientID $sa.azureTenantID }}
    azure.workload.identity/use: "true"
    {{- end }}
  {{- if or (and $sa.awsAccountID $sa.awsRoleName) (and $sa.azureClientID $sa.azureTenantID) }}
  annotations:
    {{- if and $sa.awsAccountID $sa.awsRoleName }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ $sa.awsAccountID }}:role/{{ $sa.awsRoleName }}
    {{- end }}
    {{- if and $sa.azureClientID $sa.azureTenantID }}
    azure.workload.identity/client-id: {{ $sa.azureClientID | quote }}
    azure.workload.identity/tenant-id: {{ $sa.azureTenantID | quote }}
    {{- end }}
  {{- end }}
{{- end }}
