apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-config
data:  
  {{- $publicUrl := (index .Values.web.ingress.hosts 0).host }}
  {{- $protocol := "http" }}
  {{- if .Values.web.ingress.tls }}
  {{- $protocol = "https" }}
  {{- end }}
  identity.schema.json: |
    {
        "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Person",
        "type": "object",
        "properties": {
            "traits": {
                "required": [
                    "email",
                    "name",
                    "confirmedTerms"
                ],
                "additionalProperties": false,
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string",
                        "format": "email",
                        "title": "E-Mail",
                        "minLength": 3,
                        "ory.sh/kratos": {
                            "credentials": {
                                "password": {
                                    "identifier": true
                                },
                                "passkey": {
                                    "display_name": true
                                },
                                "webauthn": {
                                    "identifier": true
                                }
                            },
                            "verification": {
                                "via": "email"
                            },
                            "recovery": {
                                "via": "email"
                            }
                        }
                    },
                    "name": {
                        "type": "string",
                        "title": "Username"
                    },
                    "confirmedTerms": {
                        "type": "boolean",
                        "title": "I agree to the terms of use ",
                        "description": "You must agree to the terms of use to use this service.",
                        "default": false,
                        "const": true
                    }
                }
            }
        }
    }
    
  kratos.yml: |
    serve: 
      public: 
        base_url: {{ $protocol }}://{{ $publicUrl }}
        cors:
          enabled: true
    identity:
      default_schema_id: identity
      schemas:
      - id: identity
        url: file:///etc/config/identity.schema.json
    courier:
      smtp:
        from_address: {{ .Values.mail.fromAddress }}
        from_name: {{ .Values.mail.fromName }}
    selfservice:
      default_browser_return_url: {{ $protocol }}://{{ $publicUrl }}/
      allowed_return_urls: 
      - {{ $protocol }}://{{ $publicUrl }}/
      methods:
        oidc:
          enabled: {{ .Values.kratos.oidc.enabled }}
          config:
          {{- if .Values.kratos.oidc.enabled }}
            providers:
            {{- range .Values.kratos.oidc.providers }}
            - id: {{ .id }}
              provider: {{ .provider }}
              client_id: {{ .clientId }}
              client_secret: "will be overwritten with env variable"
              {{- if .issuerUrl }}
              issuer_url: {{ .issuerUrl | default "" | quote }}
              {{- end }}
              mapper_url: "base64://bG9jYWwgY2xhaW1zID0gewogIGVtYWlsX3ZlcmlmaWVkOiBmYWxzZSwKfSArIHN0ZC5leHRWYXIoJ2NsYWltcycpOwoKbG9jYWwgc3RyaW5nT3JOdWxsKHYpID0KICBpZiB2ICE9IG51bGwgJiYgc3RkLnR5cGUodikgPT0gJ3N0cmluZycgJiYgdiAhPSAnJyB0aGVuIHYgZWxzZSBudWxsOwoKbG9jYWwgZmlyc3ROb25OdWxsKHZhbHVlcykgPQogIGlmIHN0ZC5sZW5ndGgodmFsdWVzKSA9PSAwIHRoZW4gbnVsbAogIGVsc2UgaWYgdmFsdWVzWzBdICE9IG51bGwgdGhlbiB2YWx1ZXNbMF0KICBlbHNlIGZpcnN0Tm9uTnVsbCh2YWx1ZXNbMTpdKTsKCnsKICBpZGVudGl0eTogewogICAgdHJhaXRzOiB7CiAgICAgIC8vIEFsbG93aW5nIHVudmVyaWZpZWQgZW1haWwgYWRkcmVzc2VzIGVuYWJsZXMgYWNjb3VudAogICAgICAvLyBlbnVtZXJhdGlvbiBhdHRhY2tzLCBlc3BlY2lhbGx5IGlmIHRoZSB2YWx1ZSBpcyB1c2VkIGZvcgogICAgICAvLyBlLmcuIHZlcmlmaWNhdGlvbiBvciBhcyBhIHBhc3N3b3JkIGxvZ2luIGlkZW50aWZpZXIuCiAgICAgIC8vCiAgICAgIC8vIFRoZXJlZm9yZSB3ZSBvbmx5IHJldHVybiB0aGUgZW1haWwgaWYgaXQgKGEpIGV4aXN0cyBhbmQgKGIpIGlzIG1hcmtlZCB2ZXJpZmllZAogICAgICAvLyBieSBHaXRIdWIuCiAgICAgIFtpZiAnZW1haWwnIGluIGNsYWltcyAmJiBjbGFpbXMuZW1haWxfdmVyaWZpZWQgdGhlbiAnZW1haWwnIGVsc2UgbnVsbF06IGNsYWltcy5lbWFpbCwKICAgICAgLy8gS2VlcCB0aGlzIHZhbHVlIHN0cmljdGx5IHN0cmluZyBmb3IgS3JhdG9zIHNjaGVtYSBjb21wYXRpYmlsaXR5LgogICAgICBuYW1lOiBmaXJzdE5vbk51bGwoWwogICAgICAgIGlmICduYW1lJyBpbiBjbGFpbXMgdGhlbiBzdHJpbmdPck51bGwoY2xhaW1zLm5hbWUpIGVsc2UgbnVsbCwKICAgICAgICBpZiAncHJlZmVycmVkX3VzZXJuYW1lJyBpbiBjbGFpbXMgdGhlbiBzdHJpbmdPck51bGwoY2xhaW1zLnByZWZlcnJlZF91c2VybmFtZSkgZWxzZSBudWxsLAogICAgICAgIGlmICdsb2dpbicgaW4gY2xhaW1zIHRoZW4gc3RyaW5nT3JOdWxsKGNsYWltcy5sb2dpbikgZWxzZSBudWxsLAogICAgICAgIGlmICd1c2VybmFtZScgaW4gY2xhaW1zIHRoZW4gc3RyaW5nT3JOdWxsKGNsYWltcy51c2VybmFtZSkgZWxzZSBudWxsLAogICAgICAgIGlmICduaWNrbmFtZScgaW4gY2xhaW1zIHRoZW4gc3RyaW5nT3JOdWxsKGNsYWltcy5uaWNrbmFtZSkgZWxzZSBudWxsLAogICAgICAgIGlmICdzdWInIGluIGNsYWltcyB0aGVuIHN0cmluZ09yTnVsbChjbGFpbXMuc3ViKSBlbHNlIG51bGwsCiAgICAgICAgJ3Vua25vd24nLAogICAgICBdKSwKICAgICAgY29uZmlybWVkVGVybXM6IHRydWUsCiAgICB9LAogIH0sCn0="
            {{- if .scope }}
              scope:
              {{- range .scope }}
              - {{ . }}
              {{- end }}
            {{- end }}
                
            {{- end }}
          {{- else }}
            providers: []
          {{- end }}
            
        webauthn:
          enabled: {{ .Values.kratos.webauthn.enabled }}
          config:
            # If set to true will use WebAuthn for passwordless flows intead of multi-factor authentication.
            passwordless: true
            rp:
              # This MUST be your root domain (not a subdomain)
              {{- $urlParts := splitList "." $publicUrl }}
              {{- if ge (len $urlParts) 2 }}
              id: {{ index $urlParts (sub (len $urlParts) 2) }}.{{ index $urlParts (sub (len $urlParts) 1) }}
              {{- else }}
              id: {{ $publicUrl }}
              {{- end }}
              # This MUST be the exact URL of the page which will prompt for WebAuthn!
              # Only the scheme (https / http), host (auth.example.org), and port (4455) are relevant. The
              # path is irrelevant.
              origins:
              - {{ $protocol }}://{{ $publicUrl }}
              # A display name which will be shown to the user on her/his device.
              display_name: DevGuard

        passkey:
          enabled: {{ .Values.kratos.passkey.enabled }}
          config:
            rp:
              {{- $urlParts := splitList "." $publicUrl }}
              {{- if ge (len $urlParts) 2 }}
              id: {{ index $urlParts (sub (len $urlParts) 2) }}.{{ index $urlParts (sub (len $urlParts) 1) }}
              {{- else }}
              id: {{ $publicUrl }}
              {{- end }}
              
              origins:
              - {{ $protocol }}://{{ $publicUrl }}
              display_name: DevGuard

        password:
          enabled: {{ .Values.kratos.password.enabled }}
        totp:
          config:
            issuer: devguard
          enabled: {{ .Values.kratos.totp.enabled }}
        lookup_secret:
          enabled: false
        link:
          enabled: false
        code:
          enabled: true
      flows:
        error:
          ui_url: {{ $protocol }}://{{ $publicUrl }}/error
        settings:
          ui_url: {{ $protocol }}://{{ $publicUrl }}/user-settings
          privileged_session_max_age: 15m
          required_aal: highest_available
        recovery:
          enabled: {{ .Values.kratos.verificationAfterSignUp.enabled }}
          ui_url: {{ $protocol }}://{{ $publicUrl }}/recovery
          use: code
          lifespan: 30m
        verification:
          enabled: {{ .Values.kratos.verificationAfterSignUp.enabled }}
          ui_url: {{ $protocol }}://{{ $publicUrl }}/verification
          use: code
          after:
            default_browser_return_url: {{ $protocol }}://{{ $publicUrl }}/
        logout:
          after:
            default_browser_return_url: {{ $protocol }}://{{ $publicUrl }}/login
        login:
          ui_url: {{ $protocol }}://{{ $publicUrl }}/login
          lifespan: 10m
        registration:
          lifespan: 10m
          ui_url: {{ $protocol }}://{{ $publicUrl }}/registration
          after:
              password:
                  hooks:
                      - hook: session
              oidc:
                  hooks:
                      - hook: session
              passkey:
                  hooks:
                      - hook: session
              webauthn:
                  hooks:
                      - hook: session
