annotations:
  charts.openshift.io/name: kubedb-webhook-server
apiVersion: v2
appVersion: v0.40.0
description: KubeDB Webhook Server by AppsCode
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
kubeVersion: '>=1.28.0-0'
maintainers:
- email: support@appscode.com
  name: appscode
name: kubedb-webhook-server
sources:
- https://github.com/kubedb
version: v0.40.0
