annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: DevGuard
  catalog.cattle.io/release-name: devguard
apiVersion: v2
appVersion: v1.6.0
description: A Helm chart for DevGuard
icon: file://assets/icons/devguard.png
name: devguard
type: application
version: 1.6.1
