{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
{{ include "epinio.labels" . | indent 4 }}
{{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    - name: {{ .Release.Name }}-http
      protocol: HTTP
      port: {{ .Values.gateway.ports.http }}
      hostname: {{ include "epinio-gateway-hostname" . }}
      allowedRoutes:
        namespaces:
          from: Same
{{- if .Values.gateway.tls.enabled }}
    - name: {{ .Release.Name }}-https
      protocol: HTTPS
      port: {{ .Values.gateway.ports.https }}
      hostname: {{ include "epinio-gateway-hostname" . }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.gateway.tls.secretName }}
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
    {{- range .Values.gateway.additionalListeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- if .hostname }}
      hostname: {{ .hostname | quote }}
      {{- end }}
      {{- if .tls }}
      tls:
        mode: {{ .tls.mode }}
        {{- if .tls.certificateRefs }}
        certificateRefs:
          {{- range .tls.certificateRefs }}
          - name: {{ .name }}
            kind: {{ .kind | default "Secret" }}
            {{- if .namespace }}
            namespace: {{ .namespace }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}

# Begin Dex Gateway
{{- if .Values.global.dex.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-dex-gateway
  labels:
{{ include "epinio.labels" . | indent 4 }}
{{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    - name: {{ .Release.Name }}-dex-http
      protocol: HTTP
      port: {{ .Values.gateway.ports.http }}
      hostname: {{ include "epinio-dex-hostname" . }}
      allowedRoutes:
        namespaces:
          from: Same
{{- if .Values.gateway.tls.enabled }}
    - name: {{ .Release.Name }}-dex-https
      protocol: HTTPS
      port: {{ .Values.gateway.ports.https }}
      hostname: {{ include "epinio-dex-hostname" . }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: dex-tls
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: Same
# dex gateway TLS conditional
{{- end }}
# dex enabled conditional
{{- end }}
# gateway conditional
{{- end }}