apiVersion: application.epinio.io/v1
kind: AppChart
metadata:
  namespace: {{ .Release.Namespace }}
  name: gateway-api-application
  labels:
    app.kubernetes.io/component: epinio
    app.kubernetes.io/instance: gateway-api-application
    app.kubernetes.io/name: epinio-gateway-api-app-chart
    app.kubernetes.io/part-of: epinio
    app.kubernetes.io/version: {{ default .Chart.AppVersion .Values.image.epinio.tag }}
spec:
  shortDescription: Epinio deployment leveraging Gateway API
  description: Epinio Gateway API support chart for application deployment
  helmChart: {{ .Values.appChart.gatewayAPI | quote }}
  settings:
    httpsRedirect:
      type: 'bool'
    appListeningPort:
      type: 'integer'
      minimum: '0'
