{
 "title": "Airlock Microgateway Block Metrics",
 "description": "Metrics on requests blocked by Airlock Microgateway.\n\nDashboard can be filtered by namespaces as well as block types.",
 "tags": [ "airlock-microgateway" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource Prometheus", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "DS_LOKI", "query": "loki" },
   {
    "name": "operator_namespace",
    "label": "Operator Namespace",
    "query": {
     "query": "label_values(microgateway_license_valid,namespace)"
    }
   },
   {
    "name": "namespace",
    "label": "Application Namespace",
    "query": {
     "query": "label_values(microgateway_license_http_rq_total,namespace)"
    }
   },
   {
    "name": "blockType",
    "label": "Block Type",
    "query": {
     "query": "label_values(microgateway_http_downstream_rq_threats_blocked_total,block_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Airlock Microgateway Block Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Requests",
   "type": "stat",
   "description": "Total number of requests processed by Airlock Microgateway.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(microgateway_license_http_rq_total{namespace=~\"${namespace:regex}\", job=~\"${operator_namespace.regex}/.*-engine\"}[$__range])))",
     "legendFormat": "Processed Requests"
    }
   ]
  },
  {
   "title": "% Blocked Requests",
   "type": "stat",
   "description": "Ratio of blocked requests vs. processed requests by Airlock Microgateway.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(microgateway_http_downstream_rq_threats_blocked_total{block_type=~\"${blockType:regex}\", namespace=~\"${namespace:regex}\", job=~\"${operator_namespace.regex}/.*-engine\"}[$__range])) / sum(increase(microgateway_license_http_rq_total{namespace=~\"${namespace:regex}\", job=~\"${operator_namespace.regex}/.*-engine\"}[$__range]))",
     "legendFormat": "Blocked Requests (%)"
    }
   ]
  },
  {
   "title": "Requests vs. % Blocks",
   "type": "timeseries",
   "description": "Requests per second processed by Airlock Microgateway along with the corresponding block rate.",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(microgateway_license_http_rq_total{namespace=~\"${namespace:regex}\", job=~\"${operator_namespace.regex}/.*-engine\"}[1m]))",
     "legendFormat": "Requests per second"
    },
    {
     "expr": "sum(rate(microgateway_http_downstream_rq_threats_blocked_total{block_type=~\"${blockType:regex}\", namespace=~\"${namespace:regex}\", job=~\"${operator_namespace.regex}/.*-engine\"}[1m])) / sum(rate(microgateway_license_http_rq_total{namespace=~\"${namespace:regex}\", job=~\"${operator_namespace.regex}/.*-engine\"}[1m]))",
     "legendFormat": "% Blocks"
    }
   ]
  },
  {
   "title": "Block Type",
   "type": "barchart",
   "description": "Blocked requests by block type.",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum by (block_type) (increase(microgateway_http_downstream_rq_threats_blocked_total{block_type=~\"${blockType:regex}\", namespace=~\"${namespace:regex}\", job=~\"${operator_namespace.regex}/.*-engine\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attack Type",
   "type": "barchart",
   "description": "Blocked requests by attack type, which are subsets of the various block types.",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "round(sum by (attack_type) (increase(microgateway_http_downstream_rq_threats_blocked_total{block_type=~\"${blockType:regex}\", namespace=~\"${namespace:regex}\", job=~\"${operator_namespace.regex}/.*-engine\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}