# Lints the kyverno-notation-aws subchart enabled alongside a created licence
# Secret, which is the supported topology: one licence, mounted by both the
# admission controller and notation-aws.
#
# license.value is required whenever license.create is true — the chart fails
# the render without it.
license:
  create: true
  value: |
    dummy-license-body-for-linting-only

kyverno-notation-aws:
  install: true
